### ISSUE TITLE
有支持SQLServer的ad认证的计划吗？

### ISSUE THREAD

**Issue by tzq1264718575** [apache/flink-cdc#1734]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
