### ISSUE TITLE
When unable gtid,how to achieve high availability when switching mysql cluster instance?

### ISSUE THREAD

**Issue by yeezychao** [apache/flink-cdc#1746]
In our company, there is a high risk of enabling gtid for existing mysql business upgrades. In this case, gtid cannot be used to ensure high availability when the mysql instance is down. Is there a solution?

**Comment by PatrickRen** [comment]
GTID should have been supported in the latest MySQL CDC connector. Please have a try with the latest version. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
