### ISSUE TITLE
Make the MySQL connector to a self-contained common library

### ISSUE THREAD

**Issue by StrikeW** [apache/flink-cdc#1782]
Hi, the MySQL connector is a very good tool to let user ingest data into Flink. But it is deep coupled with the Flink framework.
Would you consider make the MySQL connector to be a self-contained library that user can use it alone without Flink?

**Describe the solution you'd like**
Make the MySQL connector to be a self-contained library that can ingest data into other system.

**Comment by PatrickRen** [comment]
Unfortunately we can't do this as our project targets at Apache Flink.
