### ISSUE TITLE
Support table.exclude.list as Debezium does

### ISSUE THREAD

**Issue by ldwnt** [apache/flink-cdc#1817]
**Is your feature request related to a problem? Please describe.**
Parameter tableList is required in MySqlSourceConfig, so only table.include.list is effective even if table.exclude.list is specified in debezium properties.

**Describe the solution you'd like**
Remove the null check in MySqlSourceConfig:
```        this.tableList = checkNotNull(tableList);```
, or add a new parameter tableExcludeList in CDC

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
