### ISSUE TITLE
tidb cdc在列数比较多时部分列数据无法同步到目标表

### ISSUE THREAD

**Issue by Wintle** [apache/flink-cdc#1820]
使用flink sql 增加cdc souce table后，即便使用select * from table where row_n is not null也无法返回数据，而row_n是不为null的。经过测试在124列之后的数据在cdc都是null。

**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.6.0
 - Flink CDC version: 2.3.0
 - Database and version: 5.3

**To Reproduce**
1. The test data :
2. The test code :
3. The error :

**Additional Description**

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
