### ISSUE TITLE
flink cdc 什么时候能支持同步greenpulm数据库数据的？

### ISSUE THREAD

**Issue by zhangyulei000** [apache/flink-cdc#1824]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by zhangyulei000** [comment]
目前公司大部分业务数据都在greenpulm中， 公司在使用了flink 生态后 没有办法从gp中同步数据到 hive中， 是否可以提供个flink cdc connector greenpulm ？

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
