### ISSUE TITLE
Caused by: io.debezium.DebeziumException: The db history topic or its content is fully or partially missing. Please check database history topic configuration and re-execute the snapshot.

### ISSUE THREAD

**Issue by xiaojuan1981** [apache/flink-cdc#1828]
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  
 - Flink CDC version: 
 - Database and version: 

**To Reproduce**
1. The test data :
2. The test code :
3. The error :

**Additional Description**

**Comment by xiaojuan1981** [comment]
在用cdc 同步时  切换同步表 报这个错误，然后把kafka topic删除了  原来同步的表重启同步也报这个错误

**Comment by leonardBang** [comment]
你好，
 你用什么方式同步的？能贴下你的代码或者sql吗？
 切换同步表具体是怎么操作的？
 kafka topic是原始表的topic的还是切换后的表，是一个作业还是多个作业？

只有一句话描述，社区开发者没法复现你的问题，也没法协助排查。

**Comment by leonardBang** [comment]
issue 模板可以参考下之前小伙伴提的，https://github.com/ververica/flink-cdc-connectors/issues/1410

**Comment by byd-android-2017** [comment]
我也遇到同样的问题，我估计是表数据太多造成的，如超过1000W行数据，我测试过400W行，工作正常。

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
