### ISSUE TITLE
OracleIncrementalSource at Oracle CDB mode

### ISSUE THREAD

**Issue by luckes-yang** [apache/flink-cdc#1837]
**Describe the bug(Please use English)**
it could not read the PDB tables when using OracleIncrementalSource at Oracle CDB mode,Therefore, check whether the pdb is empty when creating a connection. If it is not empty, switch to the pdb session

**Environment :**
 - Flink version :  1.16.0
 - Flink CDC version: 2.4-SNAPSHOT
 - Database and version: Oracle 19c cdb

**Comment by luckes-yang** [comment]
I have commit a pr:
https://github.com/ververica/flink-cdc-connectors/pull/1836, please merge it

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
