### ISSUE TITLE
FlinkCDC采集TIDB异常报NULL触发任务重启

### ISSUE THREAD

**Issue by tanglinyi** [apache/flink-cdc#1853]
Flink任务正常启动后，小批量增量数据插入到TIDB中（万级），Flink任务采集正常。当百万级数据插入到TIDB中时，Flink任务就会触发下面NULL的异常自动重启，重启造成binlog数据丢失，尝试过设置tikv.batch_get_concurrency、tikv.importer.max_kv_batch_bytes等并发或数据量读取参数都无效，增加任务并行度也无效
![image](https://user-images.githubusercontent.com/26560146/210484709-eddb090c-c69e-4e7a-b95c-e46dc0b4585b.png)

2023-01-04 09:20:22
java.lang.NullPointerException
	at org.tikv.cdc.CDCClient.handleErrorEvent(CDCClient.java:247)
	at org.tikv.cdc.CDCClient.get(CDCClient.java:112)
	at com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction.readChangeEvents(TiKVRichParallelSourceFunction.java:240)
	at com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction.run(TiKVRichParallelSourceFunction.java:167)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:104)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:60)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:269)

看源码像是队列丢了
![1672806072321](https://user-images.githubusercontent.com/26560146/210484102-2563ffce-58fb-4d4d-be66-07f59de27220.jpg)

下面的flink任务的执行语句
CREATE TABLE tidb_dts_cdc(
id BIGINT PRIMARY KEY NOT ENFORCED,
group_id BIGINT,
business_id BIGINT,
action STRING,
create_time TIMESTAMP(3),
modify_time TIMESTAMP(3),
status INT
) WITH (
 'tikv.batch_get_concurrency' = '5',
 'connector' = 'tidb-cdc',
 'pd-addresses' = '127.0.0.1:2379',
 'database-name' = '库名',
 'table-name' = '表名',
 'scan.startup.mode' = 'latest-offset',
 'tikv.grpc.timeout_in_ms' = '300000',
 'tikv.grpc.scan.timeout_in_ms' = '600000'
 )

依赖包
<dependency>
    <groupId>com.ververica</groupId>
    <artifactId>flink-sql-connector-tidb-cdc</artifactId>
    <version>2.3.0</version>
</dependency>

**Environment :**
 - Flink version :  1.13.6
 - Flink CDC version: 2.3.0
 - Database and version: v5.4.1

**Comment by mxd-321** [comment]
根据异常对应的源码好像是这里吧？应该是从 regionClients 里 get 出来的 Region 是空的。
<img width="841" alt="image" src="https://user-images.githubusercontent.com/73006046/211230282-62ba7e39-5693-4aeb-a874-9c8d9fcd674b.png">

**Comment by mxd-321** [comment]
百万级别的数据，TiDB 表应该进行了 region split，flink-cdc 这里处理 error 就是在处理 region split，但我目前还没这种遇到 npe 的问题

**Comment by Mondler-Agmento** [comment]
这里处理region split或是region not leader报错的时候都是无限递归的去重试的逻辑，我这里会导致出现grpc线程数量暴涨的问题，不知道大佬们有碰到吗

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
