### ISSUE TITLE
java.util.concurrent.TimeoutException：Heartbeat of TaskManager with id 9c958598-9080-476a-a112-20259ce75bd1 timed out

### ISSUE THREAD

**Issue by 1648106662** [apache/flink-cdc#1856]
![图片](https://user-images.githubusercontent.com/61397150/210953321-fa0ce794-0f7d-4f84-9b31-c76c3dd8cbc5.png)

**Comment by PatrickRen** [comment]
Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
