### ISSUE TITLE
bigtable checkpoint failed

### ISSUE THREAD

**Issue by gwqlovelinux** [apache/flink-cdc#1859]
Is the map not threadsafe cause that problem ？？ flink-cdc 2.3

![image](https://user-images.githubusercontent.com/7358697/210973774-e022b7a2-ba6f-4546-a2e5-8c810efabfe9.png)

![image](https://user-images.githubusercontent.com/7358697/210973982-4973bb02-aafd-4fe8-b4ad-50bcaac95fea.png)

**Comment by PatrickRen** [comment]
Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
