### ISSUE TITLE
Does flink cdc plan to support duckdb sink

### ISSUE THREAD

**Issue by dawsongzhao** [apache/flink-cdc#1860]
**Is your feature request related to a problem? Please describe.**
Duckdb has fast query performance. If traditional RDMS data can be written to Duckdb for analysis through Flink CDC, it will be a more convenient solution

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
