### ISSUE TITLE
使用flink sql读取tidb时,部分字段值变成Null

### ISSUE THREAD

**Issue by ab111404212** [apache/flink-cdc#1883]
flink sql从tidb读取大表时超过一定列读出数据为Null,目前观测下来表的列超过一定数量(目前测试125)后,多余的列读取的值变成Null

tidb表结构
CREATE TABLE `detail` (
`id` bigint(20) NOT NULL COMMENT '主键',
`id1` bigint(20) NULL,
`id2` bigint(20) NULL,
`id3` bigint(20) NULL,
`id4` bigint(20) NULL,
`id5` bigint(20) NULL,
`id6` bigint(20) NULL,
`id7` bigint(20) NULL,
`id8` bigint(20) NULL,
`id9` bigint(20) NULL,
`id10` bigint(20) NULL,
`id11` bigint(20) NULL,
`id12` bigint(20) NULL,
`id13` bigint(20) NULL,
`id14` bigint(20) NULL,
`id15` bigint(20) NULL,
`id16` bigint(20) NULL,
`id17` bigint(20) NULL,
`id18` bigint(20) NULL,
`id19` bigint(20) NULL,
`id20` bigint(20) NULL,
`id21` bigint(20) NULL,
`id22` bigint(20) NULL,
`id23` bigint(20) NULL,
`id24` bigint(20) NULL,
`id25` bigint(20) NULL,
`id26` bigint(20) NULL,
`id27` bigint(20) NULL,
`id28` bigint(20) NULL,
`id29` bigint(20) NULL,
`id30` bigint(20) NULL,
`id31` bigint(20) NULL,
`id32` bigint(20) NULL,
`id33` bigint(20) NULL,
`id34` bigint(20) NULL,
`id35` bigint(20) NULL,
`id36` bigint(20) NULL,
`id37` bigint(20) NULL,
`id38` bigint(20) NULL,
`id39` bigint(20) NULL,
`id40` bigint(20) NULL,
`id41` bigint(20) NULL,
`id42` bigint(20) NULL,
`id43` bigint(20) NULL,
`id44` bigint(20) NULL,
`id45` bigint(20) NULL,
`id46` bigint(20) NULL,
`id47` bigint(20) NULL,
`id48` bigint(20) NULL,
`id49` bigint(20) NULL,
`id50` bigint(20) NULL,
`id51` bigint(20) NULL,
`id52` bigint(20) NULL,
`id53` bigint(20) NULL,
`id54` bigint(20) NULL,
`id55` bigint(20) NULL,
`id56` bigint(20) NULL,
`id57` bigint(20) NULL,
`id58` bigint(20) NULL,
`id59` bigint(20) NULL,
`id60` bigint(20) NULL,
`id61` bigint(20) NULL,
`id62` bigint(20) NULL,
`id63` bigint(20) NULL,
`id64` bigint(20) NULL,
`id65` bigint(20) NULL,
`id66` bigint(20) NULL,
`id67` bigint(20) NULL,
`id68` bigint(20) NULL,
`id69` bigint(20) NULL,
`id70` bigint(20) NULL,
`id71` bigint(20) NULL,
`id72` bigint(20) NULL,
`id73` bigint(20) NULL,
`id74` bigint(20) NULL,
`id75` bigint(20) NULL,
`id76` bigint(20) NULL,
`id77` bigint(20) NULL,
`id78` bigint(20) NULL,
`id79` bigint(20) NULL,
`id80` bigint(20) NULL,
`id81` bigint(20) NULL,
`id82` bigint(20) NULL,
`id83` bigint(20) NULL,
`id84` bigint(20) NULL,
`id85` bigint(20) NULL,
`id86` bigint(20) NULL,
`id87` bigint(20) NULL,
`id88` bigint(20) NULL,
`id89` bigint(20) NULL,
`id90` bigint(20) NULL,
`id91` bigint(20) NULL,
`id92` bigint(20) NULL,
`id93` bigint(20) NULL,
`id94` bigint(20) NULL,
`id95` bigint(20) NULL,
`id96` bigint(20) NULL,
`id97` bigint(20) NULL,
`id98` bigint(20) NULL,
`id99` bigint(20) NULL,
`id100` bigint(20) NULL,
`id101` bigint(20) NULL,
`id102` bigint(20) NULL,
`id103` bigint(20) NULL,
`id104` bigint(20) NULL,
`id105` bigint(20) NULL,
`id106` bigint(20) NULL,
`id107` bigint(20) NULL,
`id108` bigint(20) NULL,
`id109` bigint(20) NULL,
`id110` bigint(20) NULL,
`id111` bigint(20) NULL,
`id112` bigint(20) NULL,
`id113` bigint(20) NULL,
`id114` bigint(20) NULL,
`id115` bigint(20) NULL,
`id116` bigint(20) NULL,
`id117` bigint(20) NULL,
`id118` bigint(20) NULL,
`id119` bigint(20) NULL,
`id120` bigint(20) NULL,
`id121` bigint(20) NULL,
`id122` bigint(20) NULL,
`id123` bigint(20) NULL,
`id124` bigint(20) NULL,
`id125` bigint(20) NULL,
`id126` bigint(20) NULL,
`id127` bigint(20) NULL,
`id128` bigint(20) NULL,
`id129` bigint(20) NULL,
`id130` bigint(20) NULL,
`id131` bigint(20) NULL,
`id132` bigint(20) NULL,
`id133` bigint(20) NULL,
`id134` bigint(20) NULL,
`id135` bigint(20) NULL,
`id136` bigint(20) NULL,
`id137` bigint(20) NULL,
`id138` bigint(20) NULL,
`id139` bigint(20) NULL,
`id140` bigint(20) NULL,
`id141` bigint(20) NULL,
`id142` bigint(20) NULL,
`id143` bigint(20) NULL,
`id144` bigint(20) NULL,
`id145` bigint(20) NULL,
`id146` bigint(20) NULL,
`id147` bigint(20) NULL,
`id148` bigint(20) NULL,
`id149` bigint(20) NULL,
PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='detail';

flink表结构
CREATE TABLE `detail_src` (
`id` BIGINT NOT NULL,
`id1` BIGINT NULL,
`id2` BIGINT NULL,
`id3` BIGINT NULL,
`id4` BIGINT NULL,
`id5` BIGINT NULL,
`id6` BIGINT NULL,
`id7` BIGINT NULL,
`id8` BIGINT NULL,
`id9` BIGINT NULL,
`id10` BIGINT NULL,
`id11` BIGINT NULL,
`id12` BIGINT NULL,
`id13` BIGINT NULL,
`id14` BIGINT NULL,
`id15` BIGINT NULL,
`id16` BIGINT NULL,
`id17` BIGINT NULL,
`id18` BIGINT NULL,
`id19` BIGINT NULL,
`id20` BIGINT NULL,
`id21` BIGINT NULL,
`id22` BIGINT NULL,
`id23` BIGINT NULL,
`id24` BIGINT NULL,
`id25` BIGINT NULL,
`id26` BIGINT NULL,
`id27` BIGINT NULL,
`id28` BIGINT NULL,
`id29` BIGINT NULL,
`id30` BIGINT NULL,
`id31` BIGINT NULL,
`id32` BIGINT NULL,
`id33` BIGINT NULL,
`id34` BIGINT NULL,
`id35` BIGINT NULL,
`id36` BIGINT NULL,
`id37` BIGINT NULL,
`id38` BIGINT NULL,
`id39` BIGINT NULL,
`id40` BIGINT NULL,
`id41` BIGINT NULL,
`id42` BIGINT NULL,
`id43` BIGINT NULL,
`id44` BIGINT NULL,
`id45` BIGINT NULL,
`id46` BIGINT NULL,
`id47` BIGINT NULL,
`id48` BIGINT NULL,
`id49` BIGINT NULL,
`id50` BIGINT NULL,
`id51` BIGINT NULL,
`id52` BIGINT NULL,
`id53` BIGINT NULL,
`id54` BIGINT NULL,
`id55` BIGINT NULL,
`id56` BIGINT NULL,
`id57` BIGINT NULL,
`id58` BIGINT NULL,
`id59` BIGINT NULL,
`id60` BIGINT NULL,
`id61` BIGINT NULL,
`id62` BIGINT NULL,
`id63` BIGINT NULL,
`id64` BIGINT NULL,
`id65` BIGINT NULL,
`id66` BIGINT NULL,
`id67` BIGINT NULL,
`id68` BIGINT NULL,
`id69` BIGINT NULL,
`id70` BIGINT NULL,
`id71` BIGINT NULL,
`id72` BIGINT NULL,
`id73` BIGINT NULL,
`id74` BIGINT NULL,
`id75` BIGINT NULL,
`id76` BIGINT NULL,
`id77` BIGINT NULL,
`id78` BIGINT NULL,
`id79` BIGINT NULL,
`id80` BIGINT NULL,
`id81` BIGINT NULL,
`id82` BIGINT NULL,
`id83` BIGINT NULL,
`id84` BIGINT NULL,
`id85` BIGINT NULL,
`id86` BIGINT NULL,
`id87` BIGINT NULL,
`id88` BIGINT NULL,
`id89` BIGINT NULL,
`id90` BIGINT NULL,
`id91` BIGINT NULL,
`id92` BIGINT NULL,
`id93` BIGINT NULL,
`id94` BIGINT NULL,
`id95` BIGINT NULL,
`id96` BIGINT NULL,
`id97` BIGINT NULL,
`id98` BIGINT NULL,
`id99` BIGINT NULL,
`id100` BIGINT NULL,
`id101` BIGINT NULL,
`id102` BIGINT NULL,
`id103` BIGINT NULL,
`id104` BIGINT NULL,
`id105` BIGINT NULL,
`id106` BIGINT NULL,
`id107` BIGINT NULL,
`id108` BIGINT NULL,
`id109` BIGINT NULL,
`id110` BIGINT NULL,
`id111` BIGINT NULL,
`id112` BIGINT NULL,
`id113` BIGINT NULL,
`id114` BIGINT NULL,
`id115` BIGINT NULL,
`id116` BIGINT NULL,
`id117` BIGINT NULL,
`id118` BIGINT NULL,
`id119` BIGINT NULL,
`id120` BIGINT NULL,
`id121` BIGINT NULL,
`id122` BIGINT NULL,
`id123` BIGINT NULL,
`id124` BIGINT NULL,
`id125` BIGINT NULL,
`id126` BIGINT NULL,
`id127` BIGINT NULL,
`id128` BIGINT NULL,
`id129` BIGINT NULL,
`id130` BIGINT NULL,
`id131` BIGINT NULL,
`id132` BIGINT NULL,
`id133` BIGINT NULL,
`id134` BIGINT NULL,
`id135` BIGINT NULL,
`id136` BIGINT NULL,
`id137` BIGINT NULL,
`id138` BIGINT NULL,
`id139` BIGINT NULL,
`id140` BIGINT NULL,
`id141` BIGINT NULL,
`id142` BIGINT NULL,
`id143` BIGINT NULL,
`id144` BIGINT NULL,
`id145` BIGINT NULL,
`id146` BIGINT NULL,
`id147` BIGINT NULL,
`id148` BIGINT NULL,
`id149` BIGINT NULL,
 PRIMARY KEY(`id`)
 NOT ENFORCED
) with (
 'table-name' = 'detail',
 'pd-addresses' = 'xxxx',
 'connector' = 'tidb-cdc',
 'database-name' = 'test'
);

tidb侧插入一条数据
insert into detail(`id`,`id123`,`id124`,`id125`,`id126`,`id127`) values(1,1,2,3,4,5);

tidb侧可以查询到结果

![image](https://user-images.githubusercontent.com/8854743/215381650-7b8da614-023f-48c8-917e-ebb3bc8b9d80.png)

在flink sql查询则对应列拿到null值
![image](https://user-images.githubusercontent.com/8854743/215381770-a7bc4f59-00a5-4ea4-84ac-f28a81465cf7.png)

![image](https://user-images.githubusercontent.com/8854743/215386433-ee2c2b0f-023c-428f-88cf-b949da097509.png)

**Comment by mxd-321** [comment]
追踪源码到这里
org.tikv.common.codec.RowV2#findColID
相当于没找到这一列
<img width="759" alt="image" src="https://user-images.githubusercontent.com/73006046/215655250-a4ce51b3-7d39-4430-b513-c61bc677f3c0.png">

org.tikv.common.codec.RowV2#binarySearch
主要是这个二分查找方法，this.colID byte数组在126位之后就无法记录正数了，所以在 0～149 之间找120 也就相当于没找到
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/73006046/215655903-20de25d7-3ca8-4bfa-ae0d-6c008c6a7580.png">

不知道我分析是否正确，还请大佬来看看， @leonardBang , @GOODBOY008

**Comment by ab111404212** [comment]
@mxd-321 看起来确实是这样,走到后边查找时byte类型溢出了,有人fix嘛

**Comment by mxd-321** [comment]
确实是这样的，我自己简单修复了下，保留旧的 this.colID byte 数组，新建 int 类型数组，新的 int 数组仅在org.tikv.common.codec.RowV2#binarySearch 方法里被调用，不影响别的地方。

替换为 int 类型数组，测试OK的。

我认为更好的方式是，修复 org.tikv.common.codec.RowV2#binarySearch 方法，不用 byte 数组来帮助查找

**Comment by GOODBOY008** [comment]
> 确实是这样的，我自己简单修复了下，保留旧的 this.colID byte 数组，新建 int 类型数组，新的 int 数组仅在org.tikv.common.codec.RowV2#binarySearch 方法里被调用，不影响别的地方。
> 
> 替换为 int 类型数组，测试OK的。
> 
> 我认为更好的方式是，修复 org.tikv.common.codec.RowV2#binarySearch 方法，不用 byte 数组来帮助查找

@mxd-321 Are you will to open a pr for this issue ?

**Comment by mxd-321** [comment]
> > 确实是这样的，我自己简单修复了下，保留旧的 this.colID byte 数组，新建 int 类型数组，新的 int 数组仅在org.tikv.common.codec.RowV2#binarySearch 方法里被调用，不影响别的地方。
> > 替换为 int 类型数组，测试OK的。
> > 我认为更好的方式是，修复 org.tikv.common.codec.RowV2#binarySearch 方法，不用 byte 数组来帮助查找
> 
> @mxd-321 Are you will to open a pr for this issue ?

Hi, 我新建了一个 pr， 但是好像 ci 失败了，可以帮我看看吗？

**Comment by GOODBOY008** [comment]
> > > 确实是这样的，我自己简单修复了下，保留旧的 this.colID byte 数组，新建 int 类型数组，新的 int 数组仅在org.tikv.common.codec.RowV2#binarySearch 方法里被调用，不影响别的地方。
> > > 替换为 int 类型数组，测试OK的。
> > > 我认为更好的方式是，修复 org.tikv.common.codec.RowV2#binarySearch 方法，不用 byte 数组来帮助查找
> > 
> > 
> > @mxd-321 Are you will to open a pr for this issue ?
> 
> @GOODBOY008 Hi, 我新建了一个 pr， 但是好像 ci 失败了，可以帮我看看吗？

@mxd-321 Assigned to you and I had add comment in your pr.

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
