### ISSUE TITLE
[mysql-cdc] Add upsert changelog mode to avoid UPDATE_BEFORE records push down

### ISSUE THREAD

**Issue by yeezychao** [apache/flink-cdc#1898]
**Is your feature request related to a problem? Please describe.**
I try to use flink sql to write mysql cdc-data into redis as a dimension table for other business use. When executing `UPDATE` DML, the cdc-data will be converted into `-D (UPDATE_BEFORE)` and `+I (UPDATE_AFTER)`  two records to sink redis. However, delete first will cause other data streams to be lost(NULL) when join data, which is unacceptable.

**Describe the solution you'd like**
I think we can add support for [upsert changelog mode](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/concepts/dynamic_tables/#table-to-stream-conversion) by adding changelogMode option with mandatory primary key configuration.Basically, with `changelogMode=upsert` we will avoid `UPDATE_BEFORE` rows and we will require a primary key for the table. 

**Describe alternatives you've considered**
n/a

**Comment by yeezychao** [comment]
Hi @leonardBang, I am happy to send a PR for this if you agree this makes sense.

**Comment by tony0021074** [comment]
Postgresql connector's changelog mode can be configurated through Flink SQL API while MySQL connector's cannot.

I hope @yeezychao proposed PR would be reviewed & merged soon. @leonardBang

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).

**Comment by yeezychao** [comment]
[FLINK-35313](https://issues.apache.org/jira/browse/FLINK-35313)
