### ISSUE TITLE
Flink CDC connector with YugabyteDB

### ISSUE THREAD

**Issue by xinghua0123** [apache/flink-cdc#1899]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Are there any plan to build a Flink CDC connector with YugabyteDB, an open source Distributed SQL database? Or what's required to take this forward?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by mxd-321** [comment]
mark！

**Comment by lvyanquan** [comment]
Not support yet, maybe we can refer to https://github.com/yugabyte/debezium-connector-yugabytedb someday.

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
