### ISSUE TITLE
Supports synchronizing data from the oracle standby database

### ISSUE THREAD

**Issue by hf200012** [apache/flink-cdc#1939]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

In many financial business scenarios, the oracle database is used, generally in the active and standby mode. The main database undertakes the core transaction business, and dare not pull data from the main database in real time, otherwise it will have a great impact on the business. Small, whether it can support the function of synchronizing data from the standby database in real time

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by whmnoe4j** [comment]
这是一个很常见的需求，在电信，银行，保险，电力等行业基本都是oracle吧

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
