### ISSUE TITLE
mysql cdc restart from checkpoint failed when some binlog file has been purged

### ISSUE THREAD

**Issue by dylenWu** [apache/flink-cdc#1947]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.14.6

### Flink CDC version

2.3.X

### Database and its version

aws rds 

### Minimal reproduce step

1.start flink cdc connector job
2.clean some binlog file
3.restart from checkpoint

### What did you expect to see?

restart normally

### What did you see instead?

restart failed
io.debezium.DebeziumException: The connector is trying to read binlog starting at SourceInfo [currentGtid=null, currentBinlogFilename=mysql-bin.xxx, currentBinlogPosition=xxx, currentRowNumber=0, serverId=0, sourceTime=null, threadId=-1, currentQuery=null, tableIds=[], databaseName=null], but this is no longer available on the server. Reconfigure the connector to use a snapshot when needed. at io.debezium.connector.mysql.MySqlConnectorTask.validateSnapshotFeasibility(MySqlConnectorTask.java:329) at io.debezium.connector.mysql.MySqlConnectorTask.start(MySqlConnectorTask.java:98) at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:130) at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:759) at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:188) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by dylenWu** [comment]
i found the bug in code 
```
 private boolean checkGtidSet(MySqlOffsetContext offset) {
       ........
        // **I think the gtid  set obtained by this method is the exectuted gtid set instead of available gtid set**
        String availableGtidStr = connection.knownGtidSet();
       ......
           ......
            if (!gtidSetToReplicate.equals(nonPurgedGtidSetToReplicate)) {
                LOG.warn("Some of the GTIDs needed to replicate have been already purged");
                return false;
            }
.......
    }
```
**the right avaliable gtid set should be** 
 ```
GtidSet executedGtidSet = new GtidSet(executedGtidStr);
        final GtidSet purgedGtidSet = connection.purgedGtidSet();
        LOG.info("Server has already purged {} GTIDs", purgedGtidSet);
        GtidSet availableGtidSet = connection.subtractGtidSet(executedGtidSet, purgedGtidSet);
```

**Comment by dylenWu** [comment]
@leonardBang @wuchong If this solution works, can this issue be assigned to me, I hope I can contribute code to this project

**Comment by dylenWu** [comment]
@leonardBang i have a solution for this  and I have a solution to this problem and have been proving it in production for months，please assign it to me,i can fix it

**Comment by DivineDX** [comment]
Hi I think I encountered this issue, too, @dylenWu @leonardBang could you kindly handle it?

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
