### ISSUE TITLE
look forward to adding greenplum connectors

### ISSUE THREAD

**Issue by fengchaochao** [apache/flink-cdc#1959]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

hope 

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
