### ISSUE TITLE
look forward to adding dameng（dm8） connectors

### ISSUE THREAD

**Issue by xqhxxx** [apache/flink-cdc#1960]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

I want to obtain incremental data from Dameng database and synchronize it to PostgreSQL database. Currently, the business data is frequently modified, and using JDBC for processing is somewhat stressful.

### Solution

Database official website：https://www.dameng.com/

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
