### ISSUE TITLE
mysql cdc TableDiscoveryUtils is to slow

### ISSUE THREAD

**Issue by abc1035331062** [apache/flink-cdc#1973]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

page: com.ververica.cdc.connectors.mysql.source.utils.TableDiscoveryUtils 
function:listTables

10000 (DATABASES) * 500 (TABLES ) 
loop scan cost 3 min’s

I just need scan 10000 (DATABASES) * 1 (TABLES ) 

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by KevinZwx** [comment]
Same problem, and before `listTables ` finished, the tm is timed out, any workaround here?

**Comment by PatrickRen** [comment]
Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
