### ISSUE TITLE
[Bug] Oracle11g(AMERICAN_AMERICA.US7ASCII)   Garbled code

### ISSUE THREAD

**Issue by hellozhaoxudong** [apache/flink-cdc#1992]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

Flink v1.16.1

### Flink CDC version

flink-sql-connector-oracle-cdc-2.3.0.jar

### Database and its version

Database: Oracle 11g 
Character-Set：**AMERICAN_AMERICA.US7ASCII**

### Minimal reproduce step

1. Prepare Table
![image](https://user-images.githubusercontent.com/25793576/224685949-5feaf149-f2f1-4e2c-bc5e-15099ed1242b.png)

2. Flink SQL
`
CREATE TABLE CDC_SOURCE_9 
  (`COL1` STRING NOT NULL,
   `COL2` STRING,
   `COL3` STRING,
   `COL4` STRING,
   PRIMARY KEY(`COL1`) NOT ENFORCED) 
WITH (
   'connector' = 'oracle-cdc',
   'hostname' = '100.100.100.100',
   'port' = '1521',
   'username' = 'aaa',
   'password' = 'aaa',
   'database-name' = 'ORCL',
   'schema-name' = 'his',
   'table-name' = 'CDC_SOURCE_9',
   'debezium.database.tablename.case.insensitive' = 'false',
   'debezium.decimal.handling.mode'='string', 
   'scan.startup.mode'='latest-offset');

   select * from  CDC_SOURCE_9 ;
`

3. Insert Data
`
insert into CDC_SOURCE_9(COL1, COL2, COL3) values('2', '中文测试', '的撒基督教饿哦i放假哦i阿加多覅哦啊');

insert into CDC_SOURCE_9(COL1, COL2, COL3) values('3', '中文测试', '的撒基督教饿哦i放假哦i阿加多覅哦啊');

insert into CDC_SOURCE_9(COL1, COL2, COL3) values('4', '中文测试', '的撒基督教饿哦i放假哦i阿加多覅哦啊');
`

4. SQL-Client
![image](https://user-images.githubusercontent.com/25793576/224683736-22371811-532c-4ed4-8489-a2a3a2e19da7.png)

### What did you expect to see?

Flink-cdc-oracle need adapter Oracle AMERICAN_AMERICA.US7ASCII

### What did you see instead?

![image](https://user-images.githubusercontent.com/25793576/224683736-22371811-532c-4ed4-8489-a2a3a2e19da7.png)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by hellozhaoxudong** [comment]
Flink CDC 在 Oracle US7ASCII 编码下中文乱码的问题，我现在是使用了一个自定义函数实现的转码，解决方案：https://github.com/hellozhaoxudong/flink-xz-udf

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
