### ISSUE TITLE
Multiple source read binlogs of the same job are all assigned to SubTask-0, which may have performance problems.

### ISSUE THREAD

**Issue by lintingbin** [apache/flink-cdc#2027]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Multiple source read binlogs of the same job are all assigned to SubTask-0, which may have performance problems.
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/5699014/226238858-bd3bbc63-d7b6-4e1f-b0ad-86c6d6df3f9b.png">
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/5699014/226238965-f3ed29ed-4b21-4feb-8db1-9070a3af7a2f.png">
As shown in the above two figures, the jobs running in our production environment have several sources, and all sources are assigned to the same subtask. When there are many sources, performance problems may occur.

### Solution

When a job has multiple subtasks, different sources can be randomly assigned to different subtasks for execution to prevent all sources from being executed on one subtask.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
