### ISSUE TITLE
[Bug] CDC DataStream startup 模式为‘latest’的时候不支持添加新表同步

### ISSUE THREAD

**Issue by dashuye4** [apache/flink-cdc#2043]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink 1.15

### Flink CDC version

2.3

### Database and its version

5.7.12-log

### Minimal reproduce step

        MySqlSourceBuilder<String> mySqlSourceBuilder = MySqlSource.<String>builder()
                .hostname(hostname)
                .port(port)
                .serverId(serverId)
                .scanNewlyAddedTableEnabled(true)
                .databaseList(String.join(",", dbSet))
                .tableList(String.join(",", tableSet))
                .includeSchemaChanges(true)
                .username(user)
                .password(pssd)
                .startupOptions(StartupOptions.latest())
                .debeziumProperties(debezium_prop)
                .serverTimeZone(timeZone)
                .deserializer(new JsonDebeziumDeserializationSchema());// converts SourceRecord to JSON String

### What did you expect to see?

1. 停止Flink任务
2. 添加新表
3. scanNewlyAddedTableEnabled 特性已开启
4. startupOptions(StartupOptions.latest())
5. 从save point中恢复的时候，期望能增加新增表的CDC同步(从latest offset 开始)

### What did you see instead?

当startupOptions='latest'的时候，没有新增表的同步
当startupOptions='initial'的时候，有新增表的同步

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Fernandoize** [comment]
我也碰到了这个问题，checkpoint中存储的schema没有新加的表。

**Comment by Fernandoize** [comment]
这个应该在checkpoint恢复时强制性的从数据库获取最新的表

**Comment by dashuye4** [comment]
init 模式是没有问题的，只是latest模式不行
init 会有一个问题，就是每次新增一个表，就会阻塞所有的cdc表，直到snapshot完成，但是这些都是独立，所以这个设计很有问题
lastest 的话就不支持，新增表+checkpoint恢复，非常的蛋疼

**Comment by halfye** [comment]
这个问题现在是否有解决？

**Comment by Level1Accelerator** [comment]
+1

**Comment by Level1Accelerator** [comment]
> init 模式是没有问题的，只是latest模式不行 init 会有一个问题，就是每次新增一个表，就会阻塞所有的cdc表，直到snapshot完成，但是这些都是独立，所以这个设计很有问题 lastest 的话就不支持，新增表+checkpoint恢复，非常的蛋疼

大佬有结果了不。。我还不确定这到底是不是个bug，还是我的操作方式有问题

**Comment by Level1Accelerator** [comment]
> init 模式是没有问题的，只是latest模式不行 init 会有一个问题，就是每次新增一个表，就会阻塞所有的cdc表，直到snapshot完成，但是这些都是独立，所以这个设计很有问题 lastest 的话就不支持，新增表+checkpoint恢复，非常的蛋疼

大佬有结果了不。。我还不确定这到底是不是个bug，还是我的操作方式有问题

**Comment by Level1Accelerator** [comment]
来个大佬帮解答下疑惑啊

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
