### ISSUE TITLE
有没有支持达梦的计划呢？

### ISSUE THREAD

**Issue by sunyanqing01** [apache/flink-cdc#2045]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

有没有支持达梦的计划呢？

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by melin** [comment]
要 debezium 先支持dameng。

**Comment by DeanHere** [comment]
+1 国内信创要求越来越高

**Comment by superdevops-cn** [comment]
+1

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
