### ISSUE TITLE
请问如何按job获取单独的log和stdout？

### ISSUE THREAD

**Issue by Eason2h** [apache/flink-cdc#2072]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

目前是通过main方法实现任务启动，然后现在看flink监控页面，所有的job日志输出都在一个taskmanager内，如何单独捕获每个job的监控日志和执行日志？
![image](https://user-images.githubusercontent.com/41133494/230550755-813a9812-04b5-45d8-8e9e-1ec30a679487.png)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Eason2h** [comment]
![image](https://user-images.githubusercontent.com/41133494/230551046-a3547370-0a28-4cc1-8a5f-6c49428822e7.png)

**Comment by jikuanyu** [comment]
我自定的转换类，提交任务的时候显示类没有找到。

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
