### ISSUE TITLE
[bug] MySQL using utf8_ general_ Ci encoding, splitting will end prematurely

### ISSUE THREAD

**Issue by fuyun2024** [apache/flink-cdc#2075]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Support mysql primary keys using encoding types different from ASCII , in MySQL, the primary key uses utf8_ general_ Ci encoding type, ignoring case when sorting. The `ObjectUtils.compare(chunkEnd, max)` code comparison is based on ASCII, which will cause the split  to end prematurely.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
