### ISSUE TITLE
[Bug] [Oracle] Capture changes made by connector user & document that SYS/SYSTEM changes are not captured 

### ISSUE THREAD

**Issue by e-mhui** [apache/flink-cdc#2103]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.13

### Flink CDC version

2.3 & master

### Database and its version

oracle 11g

### Minimal reproduce step

Table column not recognized by DML parser after ALTER.

### What did you expect to see?

output data

### What did you see instead?

none.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
