### ISSUE TITLE
[Bug]  Flink CDC Orcale  Connection Pool Number settings cannot take effect

### ISSUE THREAD

**Issue by blackbryant** [apache/flink-cdc#2120]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

Flink 1.6 version 

### Flink CDC version

Flink 2.3 version 

### Database and its version

Orcale 19c

### Minimal reproduce step

connection.pool.size=50, but it cannot take effect, orcale session show 500 connections

### What did you expect to see?

Fix the problem

### What did you see instead?

I dont know

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by blackbryant** [comment]
OK

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
