### ISSUE TITLE
期望flink cdc 使用timestamp模型启动时，能够兼容读取，而不是抛出异常导致任务失败。

### ISSUE THREAD

**Issue by glsw2017** [apache/flink-cdc#2124]
### Search before asking

- [ ] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

期望flink cdc 使用timestamp模型启动时，对于表结构发生过变化情况下，能够兼容读取，而不是抛出异常导致任务失败。

![lQLPJxnOat-NscLNA4fNBjywlr2pE45FVQ8EUW9rbEAEAA_1596_903](https://github.com/ververica/flink-cdc-connectors/assets/30109514/5a89db78-f9f1-455f-ae5b-571df61174b3)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
