### ISSUE TITLE
Small file synchronization for Flink cdc s3 or oss?

### ISSUE THREAD

**Issue by scwanglijun** [apache/flink-cdc#2128]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Synchronize from Alibaba Cloud's OSS to AWS's s3 or to the company's network file server

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
What about using Flink FileSystem connector directly? https://nightlies.apache.org/flink/flink-docs-release-1.18/docs/connectors/datastream/filesystem/
