### ISSUE TITLE
Add docs for the experimental features.

### ISSUE THREAD

**Issue by ruanhang1993** [apache/flink-cdc#2164]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Add docs for the experimental features.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
