### ISSUE TITLE
[Bug] Incremental source never switches to streaming mode with disabled checkpointing and parallelism > 1

### ISSUE THREAD

**Issue by tigrulya-exe** [apache/flink-cdc#2165]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.13.6, 1.14.4, 1.15.2, 1.16.0, 1.17.0

### Flink CDC version

2.3.0, 2.4-SNAPSHOT

### Database and its version

Any connector with incremental source implementation

### Minimal reproduce step

For instance, remove 
```sql 
SET 'execution.checkpointing.interval' = '3s'; 
``` 
from `MySqlE2eITCase#testMySqlCDC()`

### What did you expect to see?

Failed job or at least error message describing that the user must enable checkpointing for the connector to work correctly 

### What did you see instead?

If parallelism of incremental source is greater than one, implementations of `SnapshotSplitAssigner` wait for completed checkpoint event to set flag field, that triggers `HybridSplitAssigner` to switch to streaming mode. If checkpointing is disabled, then flag field is never set to it's final state, which leads to the fact that the source is forever stuck in the snapshot mode. So, I think we need to forbid users to run jobs with incremental sources without enabled checkpointing. 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
