### ISSUE TITLE
Supports synchronizing data from the postgreSQL standby database?

### ISSUE THREAD

**Issue by vincent183** [apache/flink-cdc#2180]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

In many financial business scenarios, the postgreSQL database is used, generally in the active and standby mode. The main database undertakes the core transaction business, and dare not pull data from the main database in real time, otherwise it will have a great impact on the business. Small, whether it can support the function of synchronizing data from the standby database in real time

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
