### ISSUE TITLE
[Bug] if splitTable method execute fast than getNext, job will be blocked

### ISSUE THREAD

**Issue by y0908105023** [apache/flink-cdc#2187]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version
e49e22065fdd6f1026db76f81bd8ed38e81ef173

### Flink CDC version
e49e22065fdd6f1026db76f81bd8ed38e81ef173

### Database and its version

mysql:  mysql 8.0.27

### Minimal reproduce step

add `Thread.sleep(10000)` before MySqlSnapshotSplitAssigner.getNext().  lock.wait will not be notify any more, and it will wait forever.

### What did you expect to see?

job can execute normally

### What did you see instead?

nothing

### Anything else?

On MysqlCDC job start,  the method splitTable() &&  getNext() from MySqlSnapshotSplitAssigner will be execute asynchronously, the two method use one lock, and depend on the order of execution。Under special circumstances,  the job does not perform as expected

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by y0908105023** [comment]
the below jpg is job's stack, job will waiting forever, cannot handle data and throw exception
![image](https://github.com/ververica/flink-cdc-connectors/assets/8789291/0c04cc86-ff68-45f6-a84b-7aa927532fe2)

**Comment by y0908105023** [comment]
git提交地址：https://github.com/ververica/flink-cdc-connectors/pull/2188

**Comment by y0908105023** [comment]
@leonardBang 麻烦您review以下哈

**Comment by ruanhang1993** [comment]
@y0908105023 Thanks for the contribution.
I do not think there is a problem when `splitTable` method execute faster than `getNext`.
If `splitTable` method execute faster than `getNext`, the `remainingSplits` will not be empty. And we will not reach this `lock.wait` code.

**Comment by y0908105023** [comment]
@ruanhang1993  if `chunkSplitter.splitChunks(nextTable);` throws exception, and the lock wait for notify, job will be hanged, exception will not be catched. hope your response

![image](https://github.com/ververica/flink-cdc-connectors/assets/8789291/cfd2aa7b-d33b-44d0-afbf-2f91744d4119)

**Comment by ruanhang1993** [comment]
Hi, @y0908105023.

If there is an error in `splitTable`, the error will be caught and invoke `lock.notify()` at https://github.com/ververica/flink-cdc-connectors/blob/bb3b081f45d18191b9b68f52211375ebf06e8142/flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java#L556.

**Comment by y0908105023** [comment]
@ruanhang1993 if error happened, `lock.notify();` will be executed soon, and the `remainingTables` is empty, when the async method `getNext` execute, the job will wait.

**Comment by y0908105023** [comment]
@ruanhang1993 may be i can use countdown latch, if error happend, countdown latch will minus 1, the `next` method will not be wait for notify.

**Comment by y0908105023** [comment]
i met the error in my product env, and use 'lock.wait(100)` solve the problem

**Comment by y0908105023** [comment]
@ruanhang1993 looking forward to your reply

**Comment by y0908105023** [comment]
no body， no body
@ruanhang1993

**Comment by ruanhang1993** [comment]
@y0908105023 Sorry for my late reply.
I understand what you means. This makes sense. Thanks.

**Comment by y0908105023** [comment]
can this issue merge into the master branch, does i need do something else

**Comment by y0908105023** [comment]
@ruanhang1993 @leonardBang thanks for your attention, should i do something for this？

**Comment by ruanhang1993** [comment]
@y0908105023 I check the code again. And I think the problem has been fixed. 
When the exception code invoking the `notify`, we can mark sure to check it or reinvoke the `getNext` to check it because these parts are all under the lock.

For your problem, I think you should add some logs to see whether the splits is produced successfully. Thanks.

**Comment by y0908105023** [comment]
not merge any more. There is job error on compile. @ruanhang1993

**Comment by y0908105023** [comment]
@ruanhang1993 i add  log like the picture, is it ok?
<img width="837" alt="image" src="https://github.com/ververica/flink-cdc-connectors/assets/8789291/c081cda0-9e5c-4213-8610-6ab332b6bba3">

**Comment by y0908105023** [comment]
@ruanhang1993 still there

**Comment by ruanhang1993** [comment]
Maybe we could add some logs when notify and wait besides these logs.

**Comment by y0908105023** [comment]
i think it does not need a log. job will failed soon if split error

**Comment by y0908105023** [comment]
it takes long time discuss the issue, wait for your apply

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
