### ISSUE TITLE
expected to support flink-connector-db2-cd('scan.startup.mode'='specific_offsets')

### ISSUE THREAD

**Issue by dv1314** [apache/flink-cdc#2191]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Expect DB2 to support 'scan.startup.mode'='specific_offsets' as MySQL does

### Solution

https://debezium.io/documentation/reference/stable/connectors/db2.html#db2-overview

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
