### ISSUE TITLE
[Bug] flink cdc has lot of lamda class, it may leaked in flink standalone cluster after task start and stop many times

### ISSUE THREAD

**Issue by Fernandoize** [apache/flink-cdc#2196]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16.0

### Flink CDC version

2.2.1

### Database and its version

8.0

### Minimal reproduce step

-deploy a flink standalone cluster 
- start a flink cdc task and stop the task three or more times 

### What did you expect to see?

- the cluster could unload the related class in the task  and the metaspace could decrease after full gc

### What did you see instead?

- the metaspace of flink cluster always increase until oom 

### Anything else?

i dump the heap and analyse with jprofile, the ChildFirstClassLoader could not be unload because many lambda class
![Uploading image.png…]()

could someone help me give some advice, the lambda in java is common, and flink cdc used lot of lambda, i tried with a small demo, only lamda, but it could be unload when full gc.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by Fernandoize** [comment]
![image](https://github.com/ververica/flink-cdc-connectors/assets/15117983/fc5ee0f2-5050-4958-a34b-16e1e28e50b1)

**Comment by Fernandoize** [comment]
![image](https://github.com/ververica/flink-cdc-connectors/assets/15117983/bd35f0dc-ca31-498e-8c9e-0ffc41feeb23)
i stop the cdc task, but the classloader always exists

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
