### ISSUE TITLE
[Bug] Caused by: com.github.shyiko.mysql.binlog.event.deserialization.MissingTableMapEventException and lost data

### ISSUE THREAD

**Issue by dylenWu** [apache/flink-cdc#2217]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.14.6

### Flink CDC version

2.3

### Database and its version

mysql 

### Minimal reproduce step

Caused by: com.github.shyiko.mysql.binlog.event.deserialization.MissingTableMapEventException: No TableMapEventData has been found for table id:15987. Usually that means that you have started reading binary log 'within the logical event group' (e.g. from WRITE_ROWS and not proceeding TABLE_MAP

### What did you expect to see?

flink job can start from checkpoint

### What did you see instead?

no restart and loss data

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by dylenWu** [comment]
please aasign this issus to me @leonardBang

**Comment by dylenWu** [comment]
I found the reason, mainly because our binglog client was restarted during the consumption process, but the location of the restart was on the binlog of Write_rows type. As a result, when the binlog was deserialized, the corresponding table of the binlog data could not be found. Information. Because when parsing the data of the binlog type of the Write_rows type, the data of the table_map type must be parsed first.

**Comment by dylenWu** [comment]
我们可以从下面这部分代码看出问题，当出现MissingTableMapEventException这种报错的时候，程序不会抛出异常，而是继续执行，导致过程中Write_rows类型的数据被丢弃，导致数据丢失

**Comment by leonardBang** [comment]
> please aasign this issus to me @leonardBang

Assigned to you @dylenWu, please keep going, looking forward your analysis.

**Comment by dylenWu** [comment]
> 
I think we should add this logic to this method to let the client stop receiving messages, so that the queue poll() method can throw an exception
![image](https://github.com/ververica/flink-cdc-connectors/assets/22993360/64189850-5445-407c-b896-a42b39b5976a)
please review it @leonardBang

**Comment by qidian99** [comment]
@dylenWu The option to just ignore the exception is useful. I encountered a weird case where consuming from a later offset will throw the exception that the binlog file does not exist. I tried to manually specify a earlier offset, and the error showed up. In my case I'm relying on the upsert semanitcs of sink operators so having some data duplication is tolerable.

**Comment by dylenWu** [comment]
> @dylenWu The option to just ignore the exception is useful. I encountered a weird case where consuming from a later offset will throw the exception that the binlog file does not exist. I tried to manually specify a earlier offset, and the error showed up. In my case I'm relying on the upsert semanitcs of sink operators so having some data duplication is tolerable.

We cannot ignore the exception, otherwise it will cause data loss

**Comment by zhenyimo** [comment]
@dylenWu 
![image](https://github.com/ververica/flink-cdc-connectors/assets/12446913/a95d453e-0f31-4a4a-96f6-b465bde0d277)
![image](https://github.com/ververica/flink-cdc-connectors/assets/12446913/ccf6f4a0-fcf2-4c41-975e-7d7b07b9bc0e)
我看到binlogClient 碰到EOFException会重新连接,重新连接的时候会接受到一个根据当前客户端记录的binlog位置的ROTATE事件，然后会把之前残留的tableMapEventByTableId清除掉，等再次接收下一个事件的时候，就会报找不到对应的tableMapEventData，是不是因为这个问题导致的？

**Comment by dylenWu** [comment]
> @dylenWu ![image](https://user-images.githubusercontent.com/12446913/246772780-3eac9790-25eb-4734-8085-018e3a33269b.png) ![image](https://user-images.githubusercontent.com/12446913/246773688-54a1feda-71b6-48d6-8fd2-9457f9bf07a4.png) ![image](https://user-images.githubusercontent.com/12446913/246773808-2efb1e07-c979-4d4b-8218-87c5562cc008.png) ![image](https://user-images.githubusercontent.com/12446913/246774423-c52060b1-8668-4541-8506-d16164f344c8.png) 我发现当BinlogClient因为心跳超时重新连接的时候，之前保留下来的tableMapEventByTableId里的数据会因为这个ROTATE事件清除掉tableMapEventByTableId，导致下一个event的解析错误，是不是因为这个原因导致的问题？

在消费write_rows类型的binlog数据的时候，一定要先消费table_map类型的binlog获取表相关的信息，不然无法解析write_rows类型的binlog。但是当BinlogClient因为心跳超时重新连接的时候，它消费的位点可能在事务的中间，导致没有先消费table_map类型的数据，而是直接消费了write_rows类型的数据。详情请看我上面截的图。

**Comment by dylenWu** [comment]
在消费write_rows类型的binlog数据的时候，一定要先消费table_map类型的binlog获取表相关的信息，不然无法解析write_rows类型的binlog。但是当BinlogClient因为心跳超时重新连接的时候，它消费的位点可能在事务的中间，导致没有先消费table_map类型的数据，而是直接消费了write_rows类型的数据。详情请看我上面截的图。

**Comment by GuXianWei** [comment]
2.4.1也出现了这个问题 2.4.2有计划修复吗

**Comment by ldwnt** [comment]
> 在消费write_rows类型的binlog数据的时候，一定要先消费table_map类型的binlog获取表相关的信息，不然无法解析write_rows类型的binlog。但是当BinlogClient因为心跳超时重新连接的时候，它消费的位点可能在事务的中间，导致没有先消费table_map类型的数据，而是直接消费了write_rows类型的数据。详情请看我上面截的图。

感谢讲解。我想把生产环境2.1版本的cdc升级到2.4，但是因为兼容性问题（https://github.com/ververica/flink-cdc-connectors/issues/1795#issuecomment-1342237192）只能新起一个2.4版本cdc的job，不从旧job的checkpoint恢复、而是从旧job最后消费的binlog位点启动。但问题在于，这个位点通常都是write_rows类型，没有schema数据。那么【从指定的binlog位点启动】这个功能应该怎么使用呢，自己去binlog里面找非write_rows类型的最后一条记录？那么问题又来了，如果我的源库有100+张表，如何确保我选择的位点每张表都有schema呢

**Comment by shikai93** [comment]
@dylenWu do you think the PR https://github.com/ververica/flink-cdc-connectors/pull/3065 would help in this issue? This is so that the tableMapEventByTableId would not be cleared on rotate event created due to binlog client restart

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
