### ISSUE TITLE
[Bug] Debezium's database.server.name property should not be hard-coded

### ISSUE THREAD

**Issue by gunnarmorling** [apache/flink-cdc#2235]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.17.1

### Flink CDC version

2.3.0

### Database and its version

Postgres

### Minimal reproduce step

Running multiple postgres CDC connectors in one JVM process; this will trigger warnings about conflicting MBean names for the Debezium metrics beans, caused by hard-coding the logical server name property to one constant value in [here](https://github.com/ververica/flink-cdc-connectors/blob/master/flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/PostgreSQLSource.java#L157). As this name also is used to disambiguate the MBean names, it must be unique across connectors running on the same JVM (and should be unique globally anyways).

### What did you expect to see?

There should be a connector option for specifying the Debezium `database.server.name` property.

### What did you see instead?

Conflicting MBean names

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
