### ISSUE TITLE
希望在将来postgresql库支持指定时间戳消费

### ISSUE THREAD

**Issue by chen-yu342** [apache/flink-cdc#2249]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

希望将来支持指定时间戳来消费postgresql库，这样如果出了问题，不用直接回退到拉取所有的历史数据。

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
@chen-yu342 Assigned to you!

**Comment by cooltnt** [comment]
@ruanhang1993 感谢关注, 才发现有同样需求 ^_^

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
