### ISSUE TITLE
SQL server cannot read the correct table[Bug] 

### ISSUE THREAD

**Issue by ysq5202121** [apache/flink-cdc#2289]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16.0

### Flink CDC version

2.4

### Database and its version

Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)   Aug 22 2017 17:04:49   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 19044: ) (Hypervisor) 

### Minimal reproduce step

CREATE TABLE products (
    id INT,
    name STRING,
    description STRING,
    PRIMARY KEY (id) NOT ENFORCED
  ) WITH (
    'connector' = 'sqlserver-cdc',
    'hostname' = '***',
    'port' = '1433',
    'username' = 'sa',
    'password' = '***',
    'database-name' = 'inventory',
    'table-name' = 'dbo.products'
  );
![image](https://github.com/ververica/flink-cdc-connectors/assets/8586973/610edf4d-de11-4892-9b79-acd57178194e)
![image](https://github.com/ververica/flink-cdc-connectors/assets/8586973/1276cddb-3dbe-4148-90c9-6d3b4c0d5a2d)
![image](https://github.com/ververica/flink-cdc-connectors/assets/8586973/4042bbfb-73ac-433b-b107-00e5ca7eca1e)

### What did you expect to see?

OK

### What did you see instead?

If a database instance has multiple databases and multiple databases have the same table, an error reading table will occur

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
