### ISSUE TITLE
[Bug] Abnormal stop

### ISSUE THREAD

**Issue by ysq5202121** [apache/flink-cdc#2342]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16.2

### Flink CDC version

2.24.1

### Database and its version

sql server2012

### Minimal reproduce step

none

### What did you expect to see?

none

### What did you see instead?

![image](https://github.com/ververica/flink-cdc-connectors/assets/8586973/2ae60bbf-f3fa-4a92-8bbf-3663c6538d96)
Why stop every time it reaches this point

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
