### ISSUE TITLE
Support cdc catalog 

### ISSUE THREAD

**Issue by melin** [apache/flink-cdc#2370]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

implify use and avoid create table ddl

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ThisisWilli** [comment]
I'm willing to submit a PR，please assign this task to me～ @ruanhang1993 @leonardBang

**Comment by lvyanquan** [comment]
Hi, I have some confusion about what will methods of listTables, createTable mean in cdc catalog?

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
