### ISSUE TITLE
[FLINK-34805][Bug] About PostgresSql snapshot sql 

### ISSUE THREAD

**Issue by linzhicong1996** [apache/flink-cdc#2375]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.14.6

### Flink CDC version

2.4.1

### Database and its version

PostgreSQL 13.2

### Minimal reproduce step

 
In the version of flink-connector-postgres-cdc  2.4.1, snapshot SQL is generated during a full snapshot and is split according to the command of key,When running POSTGRESQL  SQL, the column will be case-sensitive. But in fact, when the SQL is generated, double quotation marks are not added to this column. Therefore POSTGRESQL converts this column to lowercase, and lead to POSTGRESQL cannot identify this column, resulting in an error.
![638901E5-7EC3-41D2-88F6-8AA4D12D54FE](https://github.com/ververica/flink-cdc-connectors/assets/94167908/7448282b-9f72-4512-b433-6a9c19bb7f6e)

package com.ververica.cdc.connectors.postgres.source.utils;

![6027352F-2643-4D3B-9D75-4CE712CBAC27](https://github.com/ververica/flink-cdc-connectors/assets/94167908/4d4d0084-a5e9-49c7-8812-8da0df8f489b)
![9966F5AB-0E48-4600-8BC6-FDF6480E7297](https://github.com/ververica/flink-cdc-connectors/assets/94167908/f937df43-d277-4495-8ca9-24460e967ece)

### What did you expect to see?

“key”

### What did you see instead?

key

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by linzhicong1996** [comment]
I modified the relevant code and the program is already working, but because I am not familiar with the whole program, I don't know if it will raise the related GUG
![Uploading 66CC19DB-2D7F-49C2-B066-D228BF58C32A.png…]()

**Comment by linzhicong1996** [comment]
![0516B4A0-7C1B-4258-A95F-E1BE08DAF2A4](https://github.com/ververica/flink-cdc-connectors/assets/94167908/0692976c-a716-46eb-8cdb-08ccbb32d588)

**Comment by ruanhang1993** [comment]
@linzhicong1996 Assign this to you. Please ping me after you raise the PR. Thanks.

**Comment by linzhicong1996** [comment]
@ruanhang1993 Code has been submitted.

[postgres] PostgresSql snapshot sql #2389

**Comment by loserwang1024** [comment]
I don't understand why PostgresDialect#isDataCollectionIdCaseSensitive always returns true, meaning that is database always use case-sensitive strategy, but this PR will change it to case-insensitive?

What kind of strategy is actually needed? @ruanhang1993 ， CC, WDYT?

**Comment by loserwang1024** [comment]
@linzhicong1996 , this issue has been migrated to https://issues.apache.org/jira/browse/FLINK-34805, Please modify your PR tittle with [FLINK-34805][xxx] xxxx as https://nightlies.apache.org/flink/flink-cdc-docs-master/docs/developer-guide/contribute-to-flink-cdc/#contributing shows

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
