### ISSUE TITLE
[Feature][Postgres] Support automatically identify newly added tables

### ISSUE THREAD

**Issue by TyrantLucifer** [apache/flink-cdc#2397]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

When we start a job with a regular expression, if a new table name matches the regular expression and is created, the event emitted by the table will not be captured and IllegalArgumentException will be thrown, causing the entire flash job to fail over.

### Solution

When instantiating EventDispatcher, InconsistenceSchemaHandler is passed in, and all internal schema information is refreshed at this time.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by loserwang1024** [comment]
Great catch! Now debezium version has been upgraded to 1.9.8, maybe we can do some changes and then rebase this PR.
