### ISSUE TITLE
[Feature][mysql] Mysql-cdc source adapts mariadb.

### ISSUE THREAD

**Issue by ThisisWilli** [apache/flink-cdc#2398]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Currently, MySQL-CDC Source will have the following problems when reading MariaDB:
1. Can not receive mariadb gtidSet event from mariadb server
2. Can not compare mariadb gtidSet when restart from specific binlog offset/

### Solution

1. overrride BinaryLogClient.requestBinaryLogStreamMaria method to get mariadb gtidSet event
2. Identify gtidSet type in BinlogOffset.compareTo method.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
