### ISSUE TITLE
[Bug]  [sqlserver cdc] the field "snapshot" is always "false" 

### ISSUE THREAD

**Issue by edmond-kk** [apache/flink-cdc#2465]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.13.6

### Flink CDC version

2.5-SNAPSHOT

### Database and its version

sqlserver 2016

### Minimal reproduce step

execute demo like
`        SqlServerSourceBuilder.SqlServerIncrementalSource<String> sqlServerSource = new SqlServerSourceBuilder()
                .hostname("xxx")
                .port(1433)
                .databaseList("xxx") // monitor sqlserver database
                .tableList("dbo.xxx") // monitor products table
                .username("xxx")
                .password("xxx")
                .deserializer(new JsonDebeziumDeserializationSchema()) // converts SourceRecord to JSON String
                .startupOptions(StartupOptions.initial())
                .build();
        DataStream<String> originDataStream = env.fromSource(sqlServerSource,WatermarkStrategy.noWatermarks(),"cdc");
        originDataStream.print();
        env.execute("Print SqlServer Snapshot + Change Stream");`

### What did you expect to see?

I can distinguish whether the data printed is snapshot or incremental by the 'snapshot' field

### What did you see instead?

the field "snapshot" is always "false" 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
