### ISSUE TITLE
[Bug] During the snapshot phase, projection is not being performed according to the user defined schema.

### ISSUE THREAD

**Issue by hzjhjjyy** [apache/flink-cdc#2470]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.17.0

### Flink CDC version

<=master

### Database and its version

such as mysql,oracle,pg,sqlserver,take oracle 11g as an example.

### Minimal reproduce step

Assuming the ABC table contains three fields, A, B, and C.

**ddl:**
CREATE TABLE ABC (
     &emsp;A BIGINT NOT NULL,
     &emsp;B STRING,
     &emsp;PRIMARY KEY(A) NOT ENFORCED
     ) WITH (
     &emsp;'connector' = 'oracle-cdc',
     &emsp;'hostname' = '192.168.xxx.xxx',
     &emsp;'port' = '1521',
     &emsp;'username' = 'xxx',
     &emsp;'password' = 'xxx',
     &emsp;'database-name' = 'xxx',
     &emsp;'schema-name' = 'xxx',
     &emsp;'table-name' = 'ABC',
     &emsp;'debezium.log.mining.strategy' = 'online_catalog',
     &emsp;'debezium.log.mining.continuous.mine' = 'true',
     &emsp;'debezium.database.tablename.case.insensitive' = 'false');

**dml:**
select * from ABC;

### What did you expect to see?

**should be:**
![查部分](https://github.com/ververica/flink-cdc-connectors/assets/57552918/b8a302e8-63dd-42ca-b2f2-67e4bd356bfa)
Projection is performed according to the schema definition, and it takes 2.534 seconds.

### What did you see instead?

**snapshot phase:**
![查全部](https://github.com/ververica/flink-cdc-connectors/assets/57552918/6504278f-4a00-43ba-8818-558a732c3f82)
The screenshot indicates that an `*` was used as the query condition, and projection was not performed as defined by the schema. And it took 3.532 seconds to execute this query.

### Anything else?

When dealing with a large amount of data and numerous partitions, this time can become quite significant.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by hzjhjjyy** [comment]
Is there any issue? or can I submit a pr?

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
