### ISSUE TITLE
[Bug] Using tidb-cdc to connect to the data source cpu usage is always high

### ISSUE THREAD

**Issue by tuyanzhang** [apache/flink-cdc#2473]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

17.1

### Flink CDC version

        <dependency>
            <groupId>com.ververica</groupId>
            <artifactId>flink-connector-tidb-cdc</artifactId>
            <version>2.4.1</version>
        </dependency>

### Database and its version

tidb 5.4.3

### Minimal reproduce step

        String xxx = "CREATE TABLE xxx (" +
                "  `id` STRING ,\n" +
                "  PRIMARY KEY (`id`) NOT ENFORCED" +
                ") WITH (" +
                "  'connector' = 'tidb-cdc',\n" +
                " 'tikv.grpc.timeout_in_ms' = '00000', " +
                "  'pd-addresses' = '127.0.0.1:2379',\n" +
                "  'database-name' = 'xxx'," +
                "  'table-name' = 'xxx'" +
                ")";

        tableEnv.executeSql(xxx);

        String xxx = "CREATE TABLE xxx (" +
                "  `id` STRING ,\n" +
                
                "  PRIMARY KEY (`id`) NOT ENFORCED" +
                ") WITH (" +
                "    'connector' = 'jdbc',\n" +
                "    'url' = 'jdbc:mysql://xxx/xxx?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true',\n" +
                "    'username' = 'xxx'," +
                "    'password' = 'xxx'," +
                "    'lookup.cache.max-rows' = '10000'," +
                "    'lookup.cache.ttl' = '5s'," +
                " 'table-name' = 'xxx'" +
                ")";

        tableEnv.executeSql(xxx);
                statementSet.addInsertSql(
                "insert into xxx select * from xxx ");

### What did you expect to see?

After the synchronization is completed, the cpu usage is reduced

### What did you see instead?

After starting the job, the CPU usage is always very high.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
