### ISSUE TITLE
[Bug] io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource : Table 'GL_001_XPHARMA_PRIVILEGE_DETAIL' won't be captured by Oracle LogMiner because its name exceeds 30 characters.

### ISSUE THREAD

**Issue by jasonhewg** [apache/flink-cdc#2475]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.14.2

### Flink CDC version

2.4.1

### Database and its version

oracle19c

### Minimal reproduce step

场景及问题：表名长度若超过30个字符长度限制，无法使用某些功能或工具，如 Oracle LogMiner。但从 Oracle 12c 版本开始，表名的最大长度已经从 30 个字符扩展到了 128 个字符了，我使用的是oracle19c，超过30个字符的表我是可以正常创建的，但使用flink cdc捕获数据时，为啥不行？

debezium-oracleconnector-oracle_logminer-change-event-source-coordinator][927]io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource : Table 'GL_001_XPHARMA_PRIVILEGE_DETAIL' won't be captured by Oracle LogMiner because its name exceeds 30 characters.

Additional explanation:
When I try to log in to oracle using sqlplus/as sysdba and execute the command:
"ALTER SYSTEM SET STREAMS_POOL_SIZE=20M SCOPE=SPFILE;" 

Also restarted Oracle. Finally, a reminder:
WARN [debezium-oracleconnector-oracle_logminer-change-event-source-coordinator][927]io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource : Table 'GL_001_XPHARMA_PRIVILEGE_DETAIL' won't be captured by Oracle LogMiner because its name exceeds 30 characters.

Can anyone completely solve this problem?Thanks.

### What did you expect to see?

正常捕获到

### What did you see instead?

而不是限制捕获

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by jasonhewg** [comment]
补充：
(1)在插入和删除操作时，捕获的数据是正常的，但更新操作时，值还是固定为0。
(2)用户与组织的关联关系表中，创建此表的DDL中，若去掉了联合主键的结束，值还是固定为0。

**Comment by lvyanquan** [comment]
LogMiner requires table or column names that are 30 characters or less.

https://docs.oracle.com/en/database/oracle/oracle-database/21/sutil/oracle-logminer-utility.html#GUID-7594F0D7-0ACD-46E6-BD61-2751136ECDB4
