### ISSUE TITLE
flink sqlserver cdc Lock Table

### ISSUE THREAD

**Issue by wsczm** [apache/flink-cdc#2481]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink 1.13.1

### Flink CDC version

flink-sql-connector-sqlserver-cdc-2.2.0.jar

### Database and its version

Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64) 
	Sep 24 2019 13:48:23 
	Copyright (C) 2019 Microsoft Corporation
	Enterprise Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor)

### Minimal reproduce step

1、Add a new field to the table
2、
Stop the Flink CDC program
3、
Close the database and then enable the cdc of the SQL server table
4、
Start the Flink program
5、
The table is locked in the production environment

### What did you expect to see?

Is there a temporary solution to this problem

### What did you see instead?

Is there a temporary solution to this problem

### Anything else?

Is there a temporary solution to this problem

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by gtk96** [comment]
use flink-sql-connector-sqlserver-cdc-2.4.1.jar
