### ISSUE TITLE
Flink-CDC是否支持opengauss3.0数据库

### ISSUE THREAD

**Issue by cncaizheng** [apache/flink-cdc#2484]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

1. 目前涉及使用到opengauss3.0数据库，想了解下flink-cdc是否支持这个数据库？
2. opengauss3.0内核使用的是postgresql9.6数据库，是否能直接使用postgre-cdc连接opengauss3.0呢？

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lvyanquan** [comment]
No support yet, maybe we can refer to https://gitee.com/opengauss/debezium someday.

**Comment by cncaizheng** [comment]
Do you have any good suggestions and examples for custom implementation

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
