### ISSUE TITLE
[Not a BUG] the best practice of the deployment of flinkcdc

### ISSUE THREAD

**Issue by binaryoak** [apache/flink-cdc#2486]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.17.1

### Flink CDC version

2.4.1

### Database and its version

NA

### Minimal reproduce step

NA

### What did you expect to see?

sorry team, this might not the correct category for my question, but I tried to post the question under the discussion section yet it looked like it was not a quite active place. 

I am just wondering what would be the best practice to deploy flinkcdc,  as from the examples in quick starts of flink-cdc-connectors, the flink cluster is deployed in session mode, yet from flink's doc, it mentions application mode is preferred in the production env.  

given there could be multiple cdc jobs, if using application mode, is it recommended to deploy the flinkcdc clusters to a single k8s cluster? and is it possible to have isolated resources for each jobs while still have a single dashboard to monitor all of the jobs? 

### What did you see instead?

NA

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Thanks for using Flink CDC! As we are migrating to Apache Flink as a sub-project, you can ask questions about using CDC via Flink user mailing list (user@flink.apache.org) if the issue still exists. Thanks!
