### ISSUE TITLE
[Bug] flink sqlserver cdc 运行 提示caused by: io.debezium.DebeziumException: The db history topic or its content is fully or partially missing, Please checkdatabase history topic configuration and re-execute the snapshot.

### ISSUE THREAD

**Issue by wsczm** [apache/flink-cdc#2502]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink 1.13.1

### Flink CDC version

2.4.1 以及2.5-SNAPSHOT

### Database and its version

Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64) 
	Sep 24 2019 13:48:23 
	Copyright (C) 2019 Microsoft Corporation
	Enterprise Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor)

### Minimal reproduce step

    val parameterTool = ExecutionEnvUtils.createParameterTool(args)
    val env = StreamExecutionEnvironment.getExecutionEnvironment
    val tEnv = StreamTableEnvironment.create(env)
    tEnv.getConfig.getConfiguration.setString("pipeline.name", "ErpOdsCDC")
    tEnv.getConfig.getConfiguration.setString("table.exec.sink.not-null-enforcer", "drop")
    val stmtSet = tEnv.createStatementSet
    //14、MES_STEPSEQ
    tEnv.executeSql(
            s"""
               |CREATE TABLE test(
               |id	bigint	,
               |bin_no	varchar(255),
               |wh_no	varchar(255),
               |mater_no	varchar(255),
               |mater_name	varchar(255),
               |mater_code	varchar(255),
               |pallet_no	varchar(255),
               |product_qty	int,
               |main_unit	varchar(255),
               |mater_spec	varchar(255),
               |line_no	varchar(255),
               |batch_no	varchar(255),
               |rack_no	varchar(255)	,
               |product_date	varchar(255),
               |is_pass	varchar(255)	,
               |PRIMARY KEY (id) NOT ENFORCED
               |) WITH (
               |'connector'     =  'sqlserver-cdc',
               |'hostname'      =  '${parameterTool.get(PropertiesConstants.SQLSERVER_HOST)}',
               |'port'          =  '${parameterTool.get(PropertiesConstants.SQLSERVER_PORT)}',
               |'username'      =  '${parameterTool.get(PropertiesConstants.SQLSERVER_USERNAME)}',
               |'password'      =  '${parameterTool.get(PropertiesConstants.SQLSERVER_PASSWORD)}',
               |'database-name' =  '${parameterTool.get(PropertiesConstants.SQLSERVER_DB)}',
               |'schema-name'   =  '${parameterTool.get(PropertiesConstants.SQLSERVER_SCHEMA)}',
               |'table-name'    =  'INTERACTIVE_INVENTORY',

               |'server-time-zone'    =  'Asia/Shanghai',
               |'scan.startup.mode'='latest-offset')""".stripMargin)
          tEnv.executeSql(
            s"""
               |CREATE TABLE test1(
               |id	bigint	,
               |bin_no	varchar(255),
               |wh_no	varchar(255),
               |mater_no	varchar(255),
               |mater_name	varchar(255),
               |mater_code	varchar(255),
               |pallet_no	varchar(255),
               |product_qty	int,
               |main_unit	varchar(255),
               |mater_spec	varchar(255),
               |line_no	varchar(255),
               |batch_no	varchar(255),
               |rack_no	varchar(255)	,
               |product_date	varchar(255),
               |is_pass	varchar(255)
               |) WITH (
               |'connector' = 'doris',
               |'fenodes' = '${parameterTool.get(PropertiesConstants.DORIS_FENODES)}',
               |'username' = '${parameterTool.get(PropertiesConstants.DORIS_USERNAME)}',
               |'password' = '${parameterTool.get(PropertiesConstants.DORIS_PASSWD)}',
               |'table.identifier' = 'mes_ods_global.ODS_MES_INTERACTIVE_INVENTORY_0P',
               |'sink.batch.interval'='${parameterTool.get(PropertiesConstants.DORIS_SINK_BATCH_INTERVAL)}',
               |'sink.properties.format' = 'json',
               |'sink.properties.strip_outer_array' = 'true',
               |'sink.enable-delete' = 'true') """.stripMargin)

    tEnv.executeSql(" insert into test1 select * from test").print()
    env.execute()

### What did you expect to see?

no error

### What did you see instead?

![image](https://github.com/ververica/flink-cdc-connectors/assets/37656284/23309ffe-9d71-4d7a-8af9-9fcac01d9b2d)

### Anything else?

i need help !!!  give me suggest to slove this problem

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lvyanquan** [comment]
can you provide log messages like 'for further processing'?
since it display which table can be processed.

**Comment by lvyanquan** [comment]
'schema-name' is unnecessary, and add schema information to 'table-name'.

**Comment by Tandoy** [comment]
> 'schema-name' is unnecessary, and add schema information to 'table-name'.

@lvyanquan 
![image](https://github.com/ververica/flink-cdc-connectors/assets/56899730/231760cf-98a2-4feb-8c4e-34dd1bc01aaa)
I am using datastream api for SQL server CDC and will also report this error.Do you have any solution? Thank you very much

**Comment by Tandoy** [comment]
> > 'schema-name' is unnecessary, and add schema information to 'table-name'.
> 
> @lvyanquan ![image](https://user-images.githubusercontent.com/56899730/278281026-231760cf-98a2-4feb-8c4e-34dd1bc01aaa.png) I am using datastream api for SQL server CDC and will also report this error.Do you have any solution? Thank you very much



After turning on CDC in my SQL server 2016, no such error occurred.

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
