### ISSUE TITLE
Allow custom Configurations for ConnectionPool

### ISSUE THREAD

**Issue by lvyanquan** [apache/flink-cdc#2509]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

In https://github.com/ververica/flink-cdc-connectors/pull/534, we introduced Hikari connection pool to reduce connection usage.
Then, we added some predefined configurations like maximumPoolSize = 20, minimumIdle = 1, connectionTimeout = 30s.
Howerver, there are still some frequently-used configurations that we haven't allow user to set, as [configurations](https://github.com/brettwooldridge/HikariCP#frequently-used) showed, which may be useful like `keepaliveTime`.

It would be better to allow user to add custom pool configurations based on their condition, like what debezium.* and [jdbc.properties.*](https://github.com/ververica/flink-cdc-connectors/pull/921) do.

### Solution

allow custom pool configurations like `hikari.*`, and add them to `HikariConfig`

### Anything else?

Requires compatibility with previous parameters like `connection.pool.size` and `connect.timeout`, and jdbcUrl、driverClassName could not be modified too. 

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
