### ISSUE TITLE
Add external listeners to obtain split information

### ISSUE THREAD

**Issue by lvyanquan** [apache/flink-cdc#2520]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

As what https://github.com/ververica/flink-cdc-connectors/pull/2453 described, we may need to add a mechanism to notify users about current split status.
[Debezium](https://debezium.io/documentation/reference/stable/configuration/notification.html#debezium-notifications-about-the-progress-of-incremental-snapshots) support notifications in 2.3, it's a helpful reference.

### Solution

1. Add event and listener definition. 
2. Notify listeners about the events in SourceEnumerator.

### Alternatives

Use Flink metric to check whether incremental reading is started

### Anything else?

Still some question to be defined:
1. What events should be contained?
2. Should we add some extra information about the slit of tables?

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
