### ISSUE TITLE
flink tidb cdc 全量跑完后，增量跑了一段时间就不会同步

### ISSUE THREAD

**Issue by SkylerZhan** [apache/flink-cdc#2566]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink 1.14.4

### Flink CDC version

2.4.1，2.3.0

### Database and its version

TiDB 6.1.0

### Minimal reproduce step

单表插入数据，无特殊操作。

### What did you expect to see?

增量数据不会停止同步

### What did you see instead?

无报错信息

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
