### ISSUE TITLE
[Bug] flink sqlserver cdc data duplication

### ISSUE THREAD

**Issue by wsczm** [apache/flink-cdc#2569]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink 1.13.1

### Flink CDC version

flink sqlserver cdc 2.4.1

### Database and its version

Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64) 
	Sep 24 2019 13:48:23 
	Copyright (C) 2019 Microsoft Corporation
	Enterprise Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor)

### Minimal reproduce step

1、编写代码
![image](https://github.com/ververica/flink-cdc-connectors/assets/37656284/a9cd0fc1-94b9-4f0a-bb84-c6b29ee97b77)
2、提交到flink集群
3、运行一段时间，cdc数据写入kafka的数据出现重复，insert,update,delete数据重复
4、flink taskmanager1日志如下：
![image](https://github.com/ververica/flink-cdc-connectors/assets/37656284/862e4ecf-597f-40f3-9e92-1a23af48fe8c)

### What did you expect to see?

无

### What did you see instead?

无

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
