### ISSUE TITLE
[improve] Alter scan.incremental.close-idle-reader.enabled Default is true

### ISSUE THREAD

**Issue by gtk96** [apache/flink-cdc#2572]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Version 2.5 will remove support for flink 1.13, which means scan.incremental.close-idle-reader.enabled the preconditions for the characteristics of the parameters are all met. Do we consider modifying this parameter to true by default, which is a significant enhancement to the user.

### Solution

Modify the parameter default value to true

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
