### ISSUE TITLE
[Bug] oracle clob

### ISSUE THREAD

**Issue by liquidmavis** [apache/flink-cdc#2573]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.12

### Flink CDC version

2.1.0

### Database and its version

oracle11

### Minimal reproduce step

In Oracle with Flink CDC, one of the fields is a CLOB. When modifying a data record, as long as the CLOB field remains unchanged, Flink CDC, during the incremental phase, will not include the CLOB field data in the received Oracle data updates. All other fields will be included. Only when modifying the CLOB field data will Flink CDC transmit it. Is this a bug? Why isn’t the CLOB field transmitted?

### What did you expect to see?

flinkcdc will transfer clob field even oralce not update this field

### What did you see instead?

1

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by e-mhui** [comment]
默认情况下，oracle 不会同步 clob 格式的数据，你可以尝试添加这个高级参数 debezium.lob.enabled=true 试试。 
<img width="1311" alt="image" src="https://github.com/ververica/flink-cdc-connectors/assets/111486498/2b745b47-576a-4013-81de-bcf5856c03be">

**Comment by fangchuanming** [comment]
i meet this problem too, when update some columns (not clob)，will get null value in clob columns maybe this is oracle official act, information from :https://access.redhat.com/documentation/zh-cn/red_hat_integration/2022.q4/html/debezium_user_guide/debezium-connector-for-oracle


```
Note
Oracle only supplies column values for CLOB, NCLOB, and BLOB data types if they’re explicitly set or changed in a SQL statement. As a result, change events never contain the value of an unchanged CLOB, NCLOB, or BLOB column. Instead, they contain placeholders as defined by the connector property, unavailable.value.placeholder.

If the value of a CLOB, NCLOB, or BLOB column is updated, the new value is placed in the after element of the corresponding update change event. The before element contains the unavailable value placeholder.
```

**Comment by Naros** [comment]
Hi, Debezium's Oracle maintainer here.

Oracle, PostgreSQL, and SQL Server have specific use cases with certain column types that will not be written to the transaction logs unless those fields are explicitly modified.  For the Oracle database, this includes data types such as CLOB, BLOB, and XMLTYPE.

What you should be observing (assuming that `lob.enabled` is set to `true`), is that you will see the Debezium unavailable placeholder injected as the value for CLOB/XMLTYPE columns and the unavailable value placeholder injected as the value for BLOB columns, except the latter is converted to a byte array to satisfy the schema type. 

For consumers, when you see the unavailable value placeholder sentinel value for these columns, your consumer should ignore that column in this case, so when using something like a JDBC sink; you simply don't add that column to your INSERT or UPDATE operation.

As @fangchuanming points out, this is not a Debezium limitation, but how the database works.  And as I mentioned above, PostgreSQL and SQL Server also have specific data types that work in an identical way.

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
