### ISSUE TITLE
[Bug] flink-postgresql-cdc buzy 100%

### ISSUE THREAD

**Issue by yanye666** [apache/flink-cdc#2586]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.17.0

### Flink CDC version

2.4.1

### Database and its version

PostgreSQL 11.9 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit

### Minimal reproduce step

At present, too many tables seem to cause this problem.

### What did you expect to see?

I thought that if I saw that the buzy was not 100% checkpoint, it would not time out, and the task would not fail.

### What did you see instead?

Here are a few questions.

one. I have 1000 tables, but only 10 tables in the test environment have data, about 600W, but according to the log, does it make sense that the snapshot phase ended in an hour?

After the checkpoint completes the snapshot phase, it will time out, causing the task to fail, and the task failure and cancellation will block until the taskmanager kill is dropped.
![image](https://github.com/ververica/flink-cdc-connectors/assets/42414099/a9f646ea-82cc-46cc-ae06-d8c491838f67)

From stack, flame diagram, database query process, all see the information with tableScheme has replacement, as shown below.
Is it possible that there are too many meters, resulting in a long-term blockage here?

![image](https://github.com/ververica/flink-cdc-connectors/assets/42414099/ae91b53e-7cb8-4d82-b7c9-b5759189ed82)
![image](https://github.com/ververica/flink-cdc-connectors/assets/42414099/77e3aa4f-41b9-4098-a710-2f5f9c87dc4e)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by yanye666** [comment]
#1458  I saw a similar mistake.
![image](https://github.com/ververica/flink-cdc-connectors/assets/42414099/5cb76b02-1f92-471b-9ba4-bff0b231f1c6)

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
