### ISSUE TITLE
SqlServer锁表问题怎么解决哇

### ISSUE THREAD

**Issue by chauxiang** [apache/flink-cdc#2589]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

SqlServer锁表问题怎么解决哇

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by instaer** [comment]
are you referring to table locking during the snaptshot?

**Comment by Tandoy** [comment]
You can upgrade the version to 2.4.0 or above

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
