### ISSUE TITLE
[flink-cdc-pipeline-connectors] Add Implementation of DataSource in MongoDB

### ISSUE THREAD

**Issue by lvyanquan** [apache/flink-cdc#2648]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

After https://github.com/ververica/flink-cdc-connectors/pull/2638 merged, we can try to add implementation in MongoDB to simulate enterprise scenarios.

You may need to wait for https://github.com/ververica/flink-cdc-connectors/issues/2642 https://github.com/ververica/flink-cdc-connectors/issues/2644 completed. 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
