### ISSUE TITLE
[flink-cdc-pipeline-connectors] Add Implementation of DataSink in Kafka

### ISSUE THREAD

**Issue by leonardBang** [apache/flink-cdc#2691]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

 Add Implementation of DataSink in Kafka

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lvyanquan** [comment]
I'm willing to do this.

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
