### ISSUE TITLE
sql server Limited date synchronization

### ISSUE THREAD

**Issue by ysq5202121** [apache/flink-cdc#2696]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16

### Flink CDC version

2.4.1

### Database and its version

sqlserver2014

### Minimal reproduce step

Support for functions  SettlementTime>=CURRENT_DATE - INTERVAL '90' DAY;
Cannot start from function definition range

### What did you expect to see?

I hope to start from the function definition range, rather than starting from all data starting positions

### What did you see instead?

I hope to synchronize the data from the last three months, but the program still starts from 2022. Although the data has not been synchronized, there has been continuous detection
![image](https://github.com/ververica/flink-cdc-connectors/assets/8586973/8488159c-a95b-4528-9ff9-1438afac46d7)
The program execution will not have any problems, but it will cause the first synchronization to be very slow

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
