### ISSUE TITLE
When will opengauss or gaussdb be supported?

### ISSUE THREAD

**Issue by wangbinhang** [apache/flink-cdc#2697]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Opengauss and Huawei Cloud's gaussdb have been widely used in the financial industry in mainland China, and I hope that flink-cdc-connectors will have plans to support opengauss and gaussdb.

### Solution

I see a two year old case here, not sure if it can work. Reference: https://github.com/dafei1288/flink-connector-opengauss

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
