### ISSUE TITLE
[Bug] BinlogOffset's comparative method may be cause incremental snapshot scan data lose

### ISSUE THREAD

**Issue by EchoLee5** [apache/flink-cdc#2794]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.14.5

### Flink CDC version

2.4.0

### Database and its version

MariaDB 10.4.13

### Minimal reproduce step

1. create mysql test table
2. create a flink cdc sql task and set the startup mode to initial
3. while writing 10000 records to the test table, start the flink task and check the number of records sent by the data.

### What did you expect to see?

The number of records is consistent with the mysql test table

### What did you see instead?

data loss or duplication

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!
![932A614C-53BF-4592-9E6C-D7F87BD6CD6F](https://github.com/ververica/flink-cdc-connectors/assets/39044001/742cd5a2-1312-47e6-9f6b-14e250198c36)

**Comment by EchoLee5** [comment]
![Dingtalk_20231201193402](https://github.com/ververica/flink-cdc-connectors/assets/39044001/701ab5c1-86ca-4564-8d6d-89578b2afa33)
I figured out that there is a problem with the logic of judging whether it is finished when reading binlog data.
BinlogOffset#compareTo(BinlogOffset that)
`        // Both offsets are missing GTIDs. Look at the servers ...
        long serverId = this.getServerId();
        long targetServerId = that.getServerId();

        if (serverId != targetServerId) {
            // These are from different servers, and their binlog coordinates are not related. So
            // the only thing we can do
            // is compare timestamps, and we have to assume that the server timestamps can be
            // compared ...
            long timestamp = this.getTimestampSec();
            long targetTimestamp = that.getTimestampSec();
            return Long.compare(timestamp, targetTimestamp);
        }`

**Comment by EchoLee5** [comment]
@leonardBang Can you help me look into this issue?

**Comment by EchoLee5** [comment]
Is it possible to remove the serverId comparison logic?

**Comment by leonardBang** [comment]
Hi, @EchoLee5  thanks for opening this ticket.
I don't get your meaning, could you describe how to reproduce this data loss issue or add a test to reproduce it?

**Comment by EchoLee5** [comment]
sorry i'm late, the way I reproduce the issue is as follows:
First, I start the task of writing test data to mysql. 
After writing part of the data, I start the flink sql task to ensure that the task will use incremental data to correct the snapshot data.
I expected that the final data consumed would be 10000, but the actual number was 9961

My mysql version is 10.3.10-MariaDB-log, **gtid is not enabled**, the test table ddl is:
```
CREATE TABLE mysql_table(
  `c1` int,
  `c2` int ,
  `c3` int,
  PRIMARY KEY (`c1`)
) 
```
The logic for sending the test table is:
  ```
  public static void main(String[] args) throws Exception {
        Connection con = null;
        PreparedStatement stmt = null;
        int count = 0;
        int totalCount = 10000;
        try {
            Class.forName(DBDRIVER);
            con = DriverManager.getConnection(DBURL, DBUSER, DBPASS);
            stmt = con.prepareStatement("insert into mysql_table(c1, c2, c3) values(?,?,?)");
            for (int i = 0; i < totalCount; i++) {
                count++;

                stmt.setInt(1, i);
                stmt.setInt(2, 2);
                stmt.setInt(3, 3);

                stmt.addBatch();
                stmt.executeBatch();
                System.out.println("Insert rows " + count);
                Thread.sleep(2);
            }
        } catch (SQLException e) {
            System.out.printf("Insert data has error " + e.getMessage());
        } finally {
            if (con != null) {
                con.close();
            }
            if (stmt != null) {
                stmt.close();
            }
        }
    }
```

flink configured includes:
```
execution.checkpointing.interval: 10s
parallelism.default: 1
pipeline.operator-chaining: false
```

flink sql is:
```
CREATE TABLE flink_cdc(
  `c1` int,
  `c2` int ,
  `c3` int,
  PRIMARY KEY (`c1`)  NOT ENFORCED
) WITH (
    'connector' = 'mysql-cdc',
       'hostname' = 'xxx',
       'port' = '33061',
       'username' = 'root',
       'password' = 'xxx',
       'database-name' = 'test',
       'table-name' = 'mysql_table',
       'scan.startup.mode' = 'initial'
);

CREATE TABLE print (
  `c1` int,
  `c2` int ,
  `c3` int,
  PRIMARY KEY (`c1`)  NOT ENFORCED
) WITH (
   'connector' = 'print'
);

insert into print select * from flink_cdc;
```

**Comment by EchoLee5** [comment]
@leonardBang I don't know if I explained it clearly. I hope you can help me look at this problem.

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
