### ISSUE TITLE
[cdc-common] Add default value of pipeline parallelism.

### ISSUE THREAD

**Issue by joyCurry30** [apache/flink-cdc#2855]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Our current 'parallelism' parameter doesn't have a default value. In cases where users do not provide input, it leads to a npe. Additionally, I believe users may not necessarily need to concern pipelines with parallelism. In the absence of a specified value, the default behavior should be to execute tasks with a single concurrency.

### Solution

Add default value for PipelineOptions#PIPELINE_PARALLELISM

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by lvyanquan** [comment]
This may overlap with [parallelism.default](https://nightlies.apache.org/flink/flink-docs-master/zh/docs/deployment/config/) in flink.conf?
And do we need to set different parallelism for source and sink in the future, as [FlinkPipelineComposer](https://github.com/ververica/flink-cdc-connectors/blob/08beca52d0ec15b42dd2f0290161056189cfb733/flink-cdc-composer/src/main/java/com/ververica/cdc/composer/flink/FlinkPipelineComposer.java#L94) use the same parallelism now.

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
