### ISSUE TITLE
[3.1][cdc-common] Add metric for DataChangeEvent

### ISSUE THREAD

**Issue by lvyanquan** [apache/flink-cdc#2858]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Currently, in Flink CDC 3.0 pipeline, numRecordIn and numRecordOut will contain all events(SchemaChangeEvent/DataChangeEvent/FlushEvent), however, user may not really care the number of FlushEvent and SchemaChangeEvent. So we need to Add metric for DataChangeEvent.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by TyrantLucifer** [comment]
Hi @lvyanquan , Could you please assign it to me?

**Comment by lvyanquan** [comment]
I don't have the permission to assign. You can raise a PR and I guess there will no be duplicate work.
