### ISSUE TITLE
[3.1][cdc-e2e] Add end to end test for pipeline.

### ISSUE THREAD

**Issue by lvyanquan** [apache/flink-cdc#2859]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Add end to end test for Flink CDC 3.0 pipeline.
You may separate it in to several subtasks like doris / starrocks.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by joyCurry30** [comment]
Hi, @lvyanquan I am will to do this task, can you assign this to me?

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
