### ISSUE TITLE
Flink CDC 3.1.0 Plan

### ISSUE THREAD

**Issue by leonardBang** [apache/flink-cdc#2861]
## Motivation

This is an umbrella issue for Flink CDC 3.1 version

## Solution

**[module] flink-cdc-common**
 * [x] #2857
 * [x] #2936
 * [x] #2943

**[module] flink-cdc-cli**
 * [ ] #2934
 * [x] #2940

**[module] flink-cdc-composer**
* [ ] #2932
* [ ] #2882
* [ ] #2854

**[module] flink-cdc-connect/flink-cdc-source-connectors**
* [x] #2869
* [x] #1747
* [x] #2867
* [x] #1152
* [ ] #2941

**[module] flink-cdc-connect/flink-cdc-pipeline-connectors**
* [ ] #2691
* [ ] #2856

**[module] flink-cdc-e2e-tests**
* [ ] #2859

**[module] docs** 
* [x] #2935
* [x] #2940

**Bug fix**
* [x] #2865
* [ ] #2853
* [x] #2966 
* [x] #2905

## Design docs
https://docs.google.com/document/d/1sC045l08hqZ8C9bVxeZdH5fY5A4Ljz__f5SqZ2Z8qrM/edit?usp=sharing

**Comment by lvyanquan** [comment]
please add this Bug fix:
Got NoSuchMethodError when running with Flink 1.17.1 and before. https://github.com/ververica/flink-cdc-connectors/issues/2943

**Comment by ChenShuai1981** [comment]
please support kubernetes deployment and auto create database

**Comment by ChenShuai1981** [comment]
please support pipeline with one source and many sinks

**Comment by miaogr86** [comment]
What are the ways to reduce memory usage during the snapshot phase?
https://github.com/ververica/flink-cdc-connectors/issues/2700
https://github.com/ververica/flink-cdc-connectors/pull/1583

**Comment by ChenShuai1981** [comment]
Support add customized type mapping like paimon does, for example, tinyint1-not-bool and bigint-unsigned-to-bigint
https://paimon.apache.org/docs/master/cdc-ingestion/mysql-cdc/

**Comment by leonardBang** [comment]
> Support add customized type mapping like paimon does, for example, tinyint1-not-bool and bigint-unsigned-to-bigint https://paimon.apache.org/docs/master/cdc-ingestion/mysql-cdc/

+1, could you open a ticket for this ?

**Comment by xiaolianghu** [comment]
Look forward to the 3.1 release soon

**Comment by klion26** [comment]
hi  @leonardBang could this [issue](https://github.com/ververica/flink-cdc-connectors/pull/2315) be fixed in 3.1.0 ?

Seems the PR has been filed a long time ago, the author active on it, and it can fix many problems.

**Comment by komiblog** [comment]
Please merge this pr #2494 to fix the MariaDB connector bug, thank you very much！

**Comment by maver1ck** [comment]
Do you have plans to include general JDBC sink ? (not only starrocks ?)

**Comment by ChenShuai1981** [comment]
Support add kafka source with debezium and canal json format

**Comment by viethung2281996** [comment]
hi @leonardBang , do you have plan or roadmap for module flink-cdc-pipeline-connectors to support pipeline with MongoDB source !

**Comment by leonardBang** [comment]
> hi @leonardBang , do you have plan or roadmap for module flink-cdc-pipeline-connectors to support pipeline with MongoDB source !

Yes, it's on the plan but maybe we consider it in next version

**Comment by ChenShuai1981** [comment]
How to handle different primary keys need between mysql and doris? For example, in mysql table we always use auto-incremental `id` column as primary key and `device_id` as biz unique key, while in doris table, considering query performance by `device_id`, we choose `device_id` + `id` columns as primary key.

**Comment by lvyanquan** [comment]
> How to handle different primary keys need between mysql and doris? For example, in mysql table we always use auto-incremental `id` column as primary key and `device_id` as biz unique key, while in doris table, considering query performance by `device_id`, we choose `device_id` + `id` columns as primary key.

@ChenShuai1981 this https://github.com/apache/flink-cdc/pull/2937 pr provide the ability to modify primary key definition.

**Comment by hyr666** [comment]
when did it support OB for Oracle(Enterprise Edition)?

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).

**Comment by xiaolianghu** [comment]
Does release 3.1.0 support the following features? Thanks!
【Support dynamically table addition in flink-cdc-base #1152】
@leonardBang
