### ISSUE TITLE
[3.1][pipeline-connectors] Add jdbc pipeline sink 

### ISSUE THREAD

**Issue by GOODBOY008** [apache/flink-cdc#2866]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

From my side and I saw in dingding group, Some user want to sync data to relation database by flink cdc.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
