### ISSUE TITLE
[cdc-connector][db2] Db2 support incremental source

### ISSUE THREAD

**Issue by gong** [apache/flink-cdc#2869]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

db2 support incremental source

### Solution

Db2 debezium is inspired by sqlserver debezium, So db2 incremental source will refer to the implementation of SQL Server CDC incremental source. 

 

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
