### ISSUE TITLE
[3.1][pipeline-connectors] Add pipeline Sink for Pulsar.

### ISSUE THREAD

**Issue by lvyanquan** [apache/flink-cdc#2879]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Add pipeline sink  support for [pulsar](https://github.com/apache/pulsar)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ToJ112** [comment]
Hi, [@lvyanquan](https://github.com/lvyanquan) I am willing to try this task, can you assign this task to me?

**Comment by lvyanquan** [comment]
@ToJ112 Hi, I don't have the authority to assign, but I raised a [pr for Kafka](https://github.com/ververica/flink-cdc-connectors/pull/2938) sink(Although there are some details to be determined), You may take it as a reference.

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
