### ISSUE TITLE
[3.1][cdc-composer] Support routing sharding tables with the same primary key into one.

### ISSUE THREAD

**Issue by lvyanquan** [apache/flink-cdc#2882]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Now we can support routing sharding tables into one only if they don't have a same value of primary key. We can improve it by add two metadata columns like `database` and `table`, and add they to a composite primary key.

You can separate it into some subtasks if needed.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
