### ISSUE TITLE
[Bug][cdc-connectors][cdc-base]  Transaction log of high_watermark read twice

### ISSUE THREAD

**Issue by loserwang1024** [apache/flink-cdc#2885]
## Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

## Flink version

1.18

## Flink CDC version

3.0

## Database and its version

anyway

## Reason
Current, read snapshot split then backfill between  [low_watermark, high_watermark], then read in stream phase between [high_watermark, +∞). The message of high_watermark will be read twice.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by link3280** [comment]
@loserwang1024 Hi, does this issue affect mysql-cdc as well (since it involves cdc-base)?  Thanks!

**Comment by loserwang1024** [comment]
@link3280，just a minor optimization. To be honest, this rarely happens because high_watermark is mostly non dml record, such as heartbeat record.

**Comment by loserwang1024** [comment]
@link3280，just a minor optimization. To be honest, this rarely happens because high_watermark is mostly non dml record, such as heartbeat record.

**Comment by link3280** [comment]
@loserwang1024 Thanks a lot for your input! The reason why I ask is that I met a data duplication issue with MySQL CDC 3.0.0 when it reads binlogs with the position set to `earliest-offset` or `timestamp`. The data showed up twice exactly. I checked the logs and all the splits were `MySqlBinlogSplit`, so the logs may be read twice. I wonder if it's the same issue.

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
