### ISSUE TITLE
MySQL database using the compress function, can provide analytic function

### ISSUE THREAD

**Issue by zhbdesign** [apache/flink-cdc#2894]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

MySQL database using the compress function, now use the base64 and udf are not parsed, the community did not see a solution, I hope to solve such problems

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
