### ISSUE TITLE
整库同步sink端支持GreenPlum

### ISSUE THREAD

**Issue by ChenpiDog** [apache/flink-cdc#2906]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

需要将业务系统数据库的数据同步至GreenPlum数仓。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
