### ISSUE TITLE
refactor: some class in flink-connector-mysql-cdc do not inherit from the base class in flink-cdc-base

### ISSUE THREAD

**Issue by cobolbaby** [apache/flink-cdc#2907]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Currently, some classes in `flink-connector-mysql-cdc` do not inherit from the base classes in `flink-cdc-base`, making the code somewhat redundant and not very tidy. such as MySqlSourceEnumerator...

Seizing this opportunity for refactoring, many functionalities implemented in `flink-connector-mysql-cdc` might be exposed in the form of interfaces, allowing other connectors to implement them. 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by cobolbaby** [comment]
In addition to inheritance issues, the subdirectory division styles of each connector are very different. If I want to add a new connector, which one should I refer to as the template?

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
