### ISSUE TITLE
[test] Support to execute the (mysql) test cases with custom database deployment

### ISSUE THREAD

**Issue by whhe** [apache/flink-cdc#2922]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Our IT workflow are  built on GitHub now, but in some cases I need to execute some of test cases locally with local deployment but not docker container. I think it will be better to add some configuration to support locally execution of test cases so that we can reuse existing test cases easily.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
