### ISSUE TITLE
[Bug] Flink-CDC3.0 sync from MySQL to StaRRocks datatype error

### ISSUE THREAD

**Issue by hophiya** [apache/flink-cdc#2925]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.18.0

### Flink CDC version

3.0

### Database and its version

StaRRocks 3.1

### Minimal reproduce step

CREATE TABLE `test` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '自增id',
......
)

### What did you expect to see?

source type:bigint ,target type:bigint ,such as :

CREATE TABLE IF NOT EXISTS test (
`id` bigint NOT NULL,

### What did you see instead?

DECIMAL(20, 0) 

### Anything else?
source db table create sql:
![image](https://github.com/ververica/flink-cdc-connectors/assets/120696271/0fc4e235-dd17-49c2-9b1d-e2fe82ae7d93)

sink table create sql:
![image](https://github.com/ververica/flink-cdc-connectors/assets/120696271/0767e10c-d2f4-4c33-8dda-fd290fa2dd9f)

source code:
![image](https://github.com/ververica/flink-cdc-connectors/assets/120696271/06e3e6d5-1e07-4522-9f14-0fe61ae81ef6)

源库MySQL中的bigint UNSIGNED 被转为 DECIMAL(20, 0) ，然而 StaRRocks中主键不支持 DECIMAL(20, 0)，报错 :
`java.sql.SQLSyntaxErrorException: Getting analyzing error. Detail message: primary key column[id] type not supported: decimal128(20, 0).
`

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by hophiya** [comment]
修改源码
/：
`            case BIGINT_UNSIGNED:
                return DataTypes.BIGINT();`

编译后，创建表成功：
![img_v3_026f_a7a2f983-0ce7-4cc0-bb30-728d9f1ea9cg](https://github.com/ververica/flink-cdc-connectors/assets/120696271/c385febc-b5a6-457e-9302-afb24fc531f3)

**Comment by loserwang1024** [comment]
@hophiya When BIGINT_UNSIGNED to DataTypes.BIGINT(), may out of bound.

**Comment by hophiya** [comment]
> @hophiya When BIGINT_UNSIGNED(0 ~2*2^32) to DataTypes.BIGINT(-2^32, 2^32-1), may out of bound. Maybe we should do some thing in sink to cast DECIMAL(20, 0) to String when as primary key.

thanks for reply,String may be better,hope for next version
