### ISSUE TITLE
flink cdc pg 不支持中文表名和中文列

### ISSUE THREAD

**Issue by rw12306** [apache/flink-cdc#2931]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.70

### Flink CDC version

2.4.1

### Database and its version

pg 13.5

### Minimal reproduce step

flink cdc 连接pg

### What did you expect to see?

希望同步pg 中文列或者中文表名不乱码。

### What did you see instead?

![image](https://github.com/ververica/flink-cdc-connectors/assets/42023195/51cf20a9-3dda-4240-9671-3c25c10ac98e)
![image](https://github.com/ververica/flink-cdc-connectors/assets/42023195/7f24f753-2afb-4ba0-9c4d-4baf3426f88f)
![image](https://github.com/ververica/flink-cdc-connectors/assets/42023195/e06033de-e119-40b5-8478-120ad40b1333)
![Z3`EZRRN952EO93S$V_C3ZU](https://github.com/ververica/flink-cdc-connectors/assets/42023195/7e14034f-b3bf-4da6-bcf5-57490ef2c8ef)

同步带中文列的字段或者是中文表时，接收到的日志显示列是乱码。

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
