### ISSUE TITLE
[Feature] Optimizing the last chunk with a large amount of data to avoid memory overflow.

### ISSUE THREAD

**Issue by lvyanquan** [apache/flink-cdc#2941]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

In certain difficulties, the last shard requires a large amount of data to be processed, resulting in memory overflow.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
