### ISSUE TITLE
[Improve] When using miniCluster, don't check 'FLINK_HOME'. 

### ISSUE THREAD

**Issue by joyCurry30** [apache/flink-cdc#2955]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

When Flink CDC uses a mini-cluster, pipelines don't need to load Flink JARs, but instead use the local environment. So, when using mini cluster, we don't need to check 'FLINK_HOME'.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by joyCurry30** [comment]
PR as #2813

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
