### ISSUE TITLE
Support modifying partition keys and primary keys of Schema.

### ISSUE THREAD

**Issue by lvyanquan** [apache/flink-cdc#2960]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Many sinks of datalakes and OLAP databases use partitions to accelerate queries, but this information is not included in the current [Schema](https://github.com/ververica/flink-cdc-connectors/blob/15a734efa09343228dc7e69e2074a16bfec40f48/flink-cdc-common/src/main/java/com/ververica/cdc/common/schema/Schema.java#L45).
We can add this API first and then consider the timing of use.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
