### ISSUE TITLE
[Bug] Jackson version conflicts among MySQL/TiDB/MongoDB connectors

### ISSUE THREAD

**Issue by link3280** [apache/flink-cdc#2983]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.14

### Flink CDC version

3.0.0

### Database and its version

MySQL 5.7

### Minimal reproduce step

Put `flink-sql-connector-tidb-cdc-3.0.0.jar`, `flink-sql-connector-mysql-cdc-3.0.0.jar` and `flink-sql-connector-mongodb-cdc-3.0.0.jar` into lib folder at Flink home (Flink 1.14 in my case), then create a MySQL CDC table and submit a simple query like `select * from mysql_cdc_table`, there would be an error:

`java.io.InvalidClassException: com.ververica.cdc.connectors.shaded.com.fasterxml.jackson.databind.cfg.MapperConfig; incompatible types for field _mapperFeatures`

It's caused by inconsistent jackson versions of the CDC connectors:

- `flink-sql-connector-mongodb-cdc-3.0.0.jar`: 2.10.2
- `flink-sql-connector-mysql-cdc-3.0.0.jar`: 2.13.2
- `flink-sql-connector-tidb-cdc-3.0.0.jar`: 2.12.3

### What did you expect to see?

All CDC connectors use the same jackson version.

### What did you see instead?

Inconsistent jackson versions among the CDC connectors which conflicts with each other.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by link3280** [comment]
I'm planning to add a `dependencyManagement` in the root pom.xml to pin the common dependencies version (especially the ones in debezium modules) . WDYT? @leonardBang

**Comment by leonardBang** [comment]
+1 from my side, thanks @link3280 for raising up this ticket.

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
