### ISSUE TITLE
Support jdbc properties in Sqlserver CDC

### ISSUE THREAD

**Issue by Alibaba-HZY** [apache/flink-cdc#2991]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Support jdbc properties in Sqlserver CDC

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
