### ISSUE TITLE
[Bug] oracle-cdc ORA-01371: Complete LogMiner dictionary not found

### ISSUE THREAD

**Issue by Toroidals** [apache/flink-cdc#2998]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink-1.15.2

### Flink CDC version

flink-connector-oracle-cdc-2.4.2

### Database and its version

oracle 12c cdb

### Minimal reproduce step

**Translation: There is no problem running the following code segment individually：**
        Properties prop = new Properties();
        prop.setProperty("log.mining.strategy", "redo_log_catalog");
        prop.setProperty("log.mining.continuous.mine", "true");
        prop.setProperty("decimal.handling.mode", "string");
        prop.setProperty("interval.handling.mode", "string");
        prop.setProperty("database.tablename.case.insensitive", "false");
        prop.setProperty("snapshot.locking.mode", "none");
        prop.setProperty("lob.enabled", "true");
        prop.setProperty("database.history.store.only.captured.tables.ddl", "true");
        prop.setProperty("database.dbname", "ORCL");
        prop.setProperty("database.pdb.name", "ORCLPDB");

        SourceFunction<String> sourceFunction = OracleSource.<String>builder()
                .url("jdbc:oracle:thin:@//192.168.xxx.xxx:1521/ORCL")
                .hostname("192.168.xxx.xxx")
                .port(1521)
                .database("ORCL")
                .schemaList("C##DBZUSER")
                .tableList("C##DBZUSER.TEST_TABLE_02")
                .username("c##dbzuser")
                .password("dbz")
                .startupOptions(StartupOptions.initial())
                .debeziumProperties(prop)
                .deserializer(new JsonDebeziumDeserializationSchema()) // converts SourceRecord to JSON String
                .build();

**Run the following code simultaneously, an error is reported：**
        Properties prop = new Properties();
        prop.setProperty("log.mining.strategy", "redo_log_catalog");
        prop.setProperty("log.mining.continuous.mine", "true");
        prop.setProperty("decimal.handling.mode", "string");
        prop.setProperty("interval.handling.mode", "string");
        prop.setProperty("database.tablename.case.insensitive", "false");
        prop.setProperty("snapshot.locking.mode", "none");
        prop.setProperty("lob.enabled", "true");
        prop.setProperty("database.history.store.only.captured.tables.ddl", "true");
        prop.setProperty("database.dbname", "ORCL");
        prop.setProperty("database.pdb.name", "ORCLPDB");

        SourceFunction<String> sourceFunction = OracleSource.<String>builder()
                .url("jdbc:oracle:thin:@//192.168.xxx.xxx:1521/ORCL")
                .hostname("192.168.xxx.xxx")
                .port(1521)
                .database("ORCL")
                .schemaList("C##DBZUSER")
                .tableList("C##DBZUSER.TEST_TABLE_01")
                .username("c##dbzuser")
                .password("dbz")
                .startupOptions(StartupOptions.initial())
                .debeziumProperties(prop)
                .deserializer(new JsonDebeziumDeserializationSchema()) // converts SourceRecord to JSON String
                .build();

error info：
java.sql.SQLException: ORA-01371: Complete LogMiner dictionary not found
ORA-06512: at "SYS.DBMS_LOGMNR", line 58
ORA-06512: at line 1

### What did you expect to see?

able to run multiple Oracle CDC instances simultaneously.

### What did you see instead?

Error occurred when running multiple oracle-cdc instances.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
