### ISSUE TITLE
Need report metric or other ways to indicate whether the current is  Incremental Snapshot Reading or binlog reading

### ISSUE THREAD

**Issue by huyuanfeng2018** [apache/flink-cdc#3001]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

I think flink cdc needs to report to the outside whether it is an incremental snapshot read. I found that after I started the task, even in the incremental snapshot read phase, the indicators

The value of `currentFetchEventTimeLag` is always 0, which will obviously cause a certain degree of misunderstanding
![image](https://github.com/ververica/flink-cdc-connectors/assets/40817998/3ba502cf-3691-432e-ba85-5f14ab638eb8)

### Solution

This information should be reported

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
