### ISSUE TITLE
[Discuss][Doc] Migrate cdc doc to flink.

### ISSUE THREAD

**Issue by GOODBOY008** [apache/flink-cdc#3002]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Give some suggestions for new cdc doc website.
demo website：http://203.24.92.93:1313/

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
New documentation website is available at https://nightlies.apache.org/flink/flink-cdc-docs-stable/
