### ISSUE TITLE
[enhancement] [ cdc-connector] [ignore no primary key table] When using regular expressions to synchronize the entire database with Flink CDC, skip tables that do not have a primary key.

### ISSUE THREAD

**Issue by everhopingandwaiting** [apache/flink-cdc#3006]
### Search before asking

- [x] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

If regular expressions are used to match the tables to be synchronized, and some tables in the database do not have a primary key, when submitting a task with Flink CDC 3.0, an error occurs. Can we add an option to skip the synchronization of tables without a primary key, such as ignore-no-primary-key-table: true?

**Flink version**
1.18

**Flink CDC version**
3.0.0

**Database and its version**
Mysql 5.7 ,  StarRocks 3.2.2

### Solution

ignore-no-primary-key-table: true

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
