### ISSUE TITLE
[enhancement] [StarRocks] When synchronizing tables using Flink CDC 3.x, is it possible to include the comments of the source table's fields when creating the target table?

### ISSUE THREAD

**Issue by everhopingandwaiting** [apache/flink-cdc#3007]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

When synchronizing tables using Flink CDC 3.x, is it possible to include the comments of the source table's fields when creating the target table?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
