### ISSUE TITLE
[Doc] How to debug the flink cdc pipeline

### ISSUE THREAD

**Issue by cobolbaby** [apache/flink-cdc#3015]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

I hope to develop the source and sink connectors of the pipeline, but I cannot set up a local development environment using idea. The idea always prompts that various dependent jars are missing.

Is it possible to improve the developer instructions in the official document, such as how to debug [CliFrontend.java](https://github.com/ververica/flink-cdc-connectors/blob/master/flink-cdc-cli/src/main/java/com/ververica/cdc/cli/CliFrontend.java) step by step.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
New documentation website is available at https://nightlies.apache.org/flink/flink-cdc-docs-stable/

**Comment by cobolbaby** [comment]
@PatrickRen  

I couldn't find any documentation related to step-by-step debugging. Please reopen it if possible.
