### ISSUE TITLE
[Doc] How to develop the flink cdc pipeline

### ISSUE THREAD

**Issue by cobolbaby** [apache/flink-cdc#3016]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

If I want to extend the implementation of end-to-end data synchronization, such as from SQL Server to PostgreSQL, SQL Server to Greenplum, PostgreSQL to Greenplum, what interface methods need to be implemented? I haven't found any relevant documentation yet.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
New documentation website is available at https://nightlies.apache.org/flink/flink-cdc-docs-stable/

**Comment by cobolbaby** [comment]
@PatrickRen  
The [document](https://nightlies.apache.org/flink/flink-cdc-docs-release-3.0/docs/developer-guide/understand-flink-cdc-api/ ) doesn't facilitate a quick start for those looking to develop pipelines. Could you provide an example using a starter project?
