### ISSUE TITLE
[Bug] tidb 从checkpoint 恢复后，不会消费任务失败时间产生的binlog数据

### ISSUE THREAD

**Issue by WenDing-Y** [apache/flink-cdc#3046]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.14.3

### Flink CDC version

3.0.0

### Database and its version

5.7.25-TiDB-v5.2.2

### Minimal reproduce step

1.set restart config
   `    // 设置从最近的检查点恢复
        env.setRestartStrategy(RestartStrategies.fixedDelayRestart(
                3, // 最大尝试重启次数
                Time.seconds(60) // 重启的时间间隔
        ));`
2.kill taskmanager
3.update db data
4.start taskmanager
5.view data print (do data print)

### What did you expect to see?

print data change between in task faild  

### What did you see instead?

fix bug

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
