### ISSUE TITLE
在指标中增加当前正在拉取的表

### ISSUE THREAD

**Issue by BaoPiao** [apache/flink-cdc#3052]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.
flink-cdc-connector版本：3.0.1

### Motivation

实时感知当前任务正在拉取的表

### Solution

可在MySqlPipelineRecordEmitter的构造函数中，通过入参sourceReaderMetrics和sourceConfig向指标中汇报拉取表列表

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
