### ISSUE TITLE
[Bug] MongoCDC checkpoint error

### ISSUE THREAD

**Issue by illsiveblue** [apache/flink-cdc#3053]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.15.2

### Flink CDC version

2.4.1

### Database and its version

5

### Minimal reproduce step

When MongoCDC starts from a checkpoint, if there have been no data changes (such as inserts, updates, or deletes) before the checkpoint, starting from the checkpoint will still initiate the capture of all data. Only after data changes occur, will the initialization data not be captured.

### What did you expect to see?

After starting from a checkpoint, regardless of whether there have been data changes in the database, data will be captured starting from the offset.

### What did you see instead?

capture all data

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
