### ISSUE TITLE
Oracle add data has error

### ISSUE THREAD

**Issue by ccczhouxin** [apache/flink-cdc#3056]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.18.1

### Flink CDC version

3.0.0

### Database and its version

oracle 11g

### Minimal reproduce step

I run the document at https://ververica.github.io/flink-cdc-connectors/release-3.0/content/connectors/oracle-cdc.html,when i add a data to table,it has some error     
   Properties debeziumProperties = new Properties();
        debeziumProperties.setProperty("log.mining.strategy", "online_catalog");
        debeziumProperties.setProperty("include.schema.changes", "true");
        debeziumProperties.setProperty("value.converter.schemas.enable", "true");

        OracleSourceBuilder.OracleIncrementalSource oracleChangeEventSource =
                new OracleSourceBuilder()
                        .hostname("hostname")
                        .port(1521)
                        .databaseList("ORCL")
                        .schemaList("FLINKUSER")
                        .tableList("FLINKUSER.CREATETABLE")
                        .username("flinkuser")
                        .password("flinkpw")
                        .deserializer(new JsonDebeziumDeserializationSchema())
                        .includeSchemaChanges(true) // output the schema changes as well
                        .startupOptions(StartupOptions.initial())
                        .debeziumProperties(debeziumProperties)
                        .splitSize(2)
                        .build();

        StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
        env.enableCheckpointing(3000L);

        DataStreamSource oracleChangeEventStream = env.fromSource(
                        oracleChangeEventSource,
                        WatermarkStrategy.noWatermarks(),
                        "OracleParallelSource")
                .setParallelism(4)
                .setParallelism(1);

        oracleChangeEventStream.print();

![image](https://github.com/ververica/flink-cdc-connectors/assets/43168824/14d5e0e2-daed-4d8a-bce5-1ed83ccd5c88)

### What did you expect to see?

Is it my configuration problem

### What did you see instead?

null error

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by ccczhouxin** [comment]
When i add column at table,id has other error. 
![image](https://github.com/ververica/flink-cdc-connectors/assets/43168824/c658f28e-fb2d-4265-963b-9a933741f590)

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
