### ISSUE TITLE
[Bug] mongocd从checkpoint启动，没有changelog的情况下一直从头读取

### ISSUE THREAD

**Issue by illsiveblue** [apache/flink-cdc#3057]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.15.2

### Flink CDC version

2.4.1

### Database and its version

5.0

### Minimal reproduce step

1.启动mongocdc抓取数据表，一共15条数据
2.表没有变动
3.cancel flink job
4.从checkpoint启动，仍然会抓到初始化的15条数据

### What did you expect to see?

希望从checkpoint启动，继续从15条数据之后的变动开始抓取

### What did you see instead?

数据没有变动时，存储的checkpoint的_metadata文件中，序列化的对象存储的是"sourceOffset":{"_id":"{\"_id\": {\"$oid\": \"64dae5e91e8e1f5af9231663\"}, \"copyingData\": true}","copy":"true"}}
当抓取的数据表有增删改之后，序列化对象存储的是"sourceOffset":{"_id":"{\"_data\": \"8265BB3EAC000000012B022C0100296E5A10042AF5B81541204F159E51F090440D054746645F696400646439158A0B060F84DFC103250004\"}"}}
当数据表有增删改之后，存储_data的数据，这时checkpoint能够从当前节点向后取数据，但是如果没有表的增删改，数据就一直从初始化数据开始取

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
