### ISSUE TITLE
整库多表同步，其中一个表同步失败，怎么恢复？

### ISSUE THREAD

**Issue by melin** [apache/flink-cdc#3061]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

整库多表同步，其中一个表同步失败，怎么恢复？

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
