### ISSUE TITLE
[Bug] 3.0 StarRocksDataSink不支持 flink1.14  【java.lang.NoClassDefFoundError: org/apache/flink/api/connector/sink2/Sink】

### ISSUE THREAD

**Issue by cleverUtd** [apache/flink-cdc#3062]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.14.6

### Flink CDC version

3.0.0

### Database and its version

starrocks 2.5.2

### Minimal reproduce step

按照以下教程操作的：
https://ververica.github.io/flink-cdc-connectors/master/content/%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B/mysql-starrocks-pipeline-tutorial-zh.html

### What did you expect to see?

成功读取mysql，落库starrocks

### What did you see instead?

![image](https://github.com/ververica/flink-cdc-connectors/assets/3830880/b541dce5-3a64-49ee-ba97-c273b2131491)

读取mysql成功，创建StarRocksDataSink失败

### Anything else?

![image](https://github.com/ververica/flink-cdc-connectors/assets/3830880/233bd8d0-20d9-437a-a7bc-84f918158dd4)

官网宣称flinkcdc 3.0支持1.14.* 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by dufeng1010** [comment]
org/apache/flink/api/connector/sink2/Sink.java is be added to flink project in flink1.15 version. i think 3.0.* don't support flink1.14 version. i think docs is not correct.

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
