### ISSUE TITLE
[Bug] After starting Streaming ELT from MySQL to StarRocks using Flink CDC 3.0, the newly created tables are not being synchronized.

### ISSUE THREAD

**Issue by tatianguiqu** [apache/flink-cdc#3068]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

image flink:scala_2.12-java8， consistent with the doc

### Flink CDC version

Both 3.0.0 and 3.0.1 have the same issue

### Database and its version

debezium/example-mysql:1.1，registry.starrocks.io/starrocks/allin1-ubuntu 
consistent with the doc

### Minimal reproduce step

Upon following the steps in the documentation, after completing the 'Submit job using FlinkCDC cli' step, I created a new table orders_1  and inserted columns into it
Here is the schema for the orders_1 table I created:
CREATE TABLE `orders_1` (
`id` INT NOT NULL,
`price` DECIMAL(10,2) NOT NULL,
PRIMARY KEY (`id`)
);

### What did you expect to see?

Table orderrs_1 should be synchronized to starrocks

### What did you see instead?

A few days ago, while testing and inserting columns into 'orders_1', an error stating 'schema orders_1 does not exist' occurred. Now, I am unable to reproduce this error. However, the issue of CDC showing no response to the new table 'orders_1' persists.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by avatarTaier** [comment]
Seems like a bug, or is it not supported?

**Comment by avatarTaier** [comment]
@ruanhang1993
