### ISSUE TITLE
[Feature] CDC Action supports update and delete record (logical deletion) 

### ISSUE THREAD

**Issue by melin** [apache/flink-cdc#3075]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation
There is a very common scenario in government departments (such as health insurance data reporting). When data is reported from the city to the province and from the province to the country, deleted and modified data must be retained to prevent data from being deleted at the next level.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by klion26** [comment]
+1 for the feature

@melin could you please change the description to English.

**Comment by lvyanquan** [comment]
This is indeed a universal requirement. 
However, currently our schemaChangeEvent is not bound to the Checkpoint timing, so we have not implemented exactly once write and rely on primary key deduplication. 

This can be added to the Todo work item.

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
