### ISSUE TITLE
[Feature][Pipeline] Flink CDC pipeline transform supports type conversion

### ISSUE THREAD

**Issue by aiwenmo** [apache/flink-cdc#3078]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

To be supplemented.

### Solution

To be supplemented.

### Alternatives

None.

### Anything else?

To be supplemented.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
