### ISSUE TITLE
[Feature] Flink CDC Oracle support tables without primary keys and scan newly added tables

### ISSUE THREAD

**Issue by Fly365** [apache/flink-cdc#3095]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation
   In the  Incremental Snapshot based DataStream,I hope this support, thank you!
-  Like MySQL CDC support tables that do not have a primary key. To use a table without primary keys, you must configure the scan.incremental.snapshot.chunk.key-column option and specify one non-null field.
- Scan Newly Added Tables feature enables you add new tables to monitor for existing running pipeline, the newly added tables will read theirs snapshot data firstly and then read their changelog automatically.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
