### ISSUE TITLE
postgresql cdc 从检查点恢复时 只能恢复一次吗？

### ISSUE THREAD

**Issue by anxinyh** [apache/flink-cdc#3103]
任务保存了检查点，这个时候停止了任务，在停止期间假如新增了一条数据
然后任务启动的时候选择从上个jobId最新的chk进行恢复，这个时候任务能获取到那条数据
但如果任务再重启，依然从刚才那个位置进行恢复，就无法获取到那条数据了

将数据源换成mysql后，只要从指定的检查点恢复时，在这个检查点之后产生的数据变化，任务启动都会获取到

请问这种情况是postgresql哪里的问题呢？
![WX20240306-121919](https://github.com/apache/flink-cdc/assets/41863942/cfac0f07-5fa0-4ca2-894f-74dc454c55f4)

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
