### ISSUE TITLE
[bug] mysql cdc doris 设置 debezium.table.exclude.list 属性无效

### ISSUE THREAD

**Issue by laizuan** [apache/flink-cdc#3104]
![6be9f2e549f63edbb49fde8cc955cc5a](https://github.com/apache/flink-cdc/assets/27326994/a67f5e24-d46d-4d4c-977a-d24bf3984810)

flink cdc: 3.0.1
flink: 1.8.1
mysql: 8.x
doris: 2.x

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
