### ISSUE TITLE
The Document URL in README.md file  was invalid

### ISSUE THREAD

**Issue by hnbian** [apache/flink-cdc#3105]
<img width="957" alt="image" src="https://github.com/apache/flink-cdc/assets/12964828/fde93c8c-76c0-4fa0-9f31-7d3fd9977c2b">
<img width="1058" alt="image" src="https://github.com/apache/flink-cdc/assets/12964828/e56f3719-1877-4939-85f3-c5c4f489af43">
<img width="903" alt="image" src="https://github.com/apache/flink-cdc/assets/12964828/3811f690-a815-4004-8824-b7cce3a75bf2">

**Comment by hnbian** [comment]
https://github.com/apache/flink-cdc/pull/3106

**Comment by PatrickRen** [comment]
New documentation website is available at https://nightlies.apache.org/flink/flink-cdc-docs-stable/
