### ISSUE TITLE
Error on Postgres-CDC using incremental snapshot with UUID column as PK

### ISSUE THREAD

**Issue by olivier-derom** [apache/flink-cdc#3108]
A majority of our Postgres databases use UUIDs as primary keys.
When we enable 'scan.incremental.snapshot.enabled = true', Flink-CDC will try to split into chunks.
The splitTableIntoChunks function relies on the queryMinMax function, which fails when trying to calculate the MIN(UUID) and MAX(UUID), as that is not supported in Postgres.

Is there a way around this?

When we convert our column to VARCHAR, rather than UUID, everything seems to work.
We did not find a way to cast our UUIDs to VARCHAR while splitting them into chunks without editing the source code or altering the source table.

Disabling incremental snapshots also fixes the issue, as we do not split into chunks anymore, but this would mean we get a global read lock on the data before snapshot reading, which we want to avoid.

Thanks in advance for the help!

**Comment by olivier-derom** [comment]
I figured this is a limitation of Postgres and not Flink-CDC, so tried to create my own min(uuid, uuid) and max(uuid, uuid) as well as aggregate min(uuid) and max(uuid).
They work perfectly when I execute the SQL statement myself on the database, but Flink-CDC still says 'function min(uuid) does not exist'.
Does it somehow not have access to custom functions?
The database connection in Flink-CDC is made using the same credentials as I created the function with, so the user should have access.

**Comment by olivier-derom** [comment]
@drorventura 
As per my last reply, I indeed created my own functions that are able to calculate the min/max of UUID's, similar to how you defined them.
While this allows us to select min/max(UUID) when executing a query on the database in an SQL client like DBeaver, Flink was not able to use these functions, and I haven't figured out how to make it work yet.

**Comment by loserwang1024** [comment]
@olivier-derom  It seems a bug, could you please create a [jira ](https://issues.apache.org/jira/browse/FLINK-34952)and fix it? If you don't have time, I'd like to help you todo it.

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).

**Comment by yiqinghuang** [comment]
Hi @PatrickRen, is there an official solution on this issue now?

**Comment by edwardzcn-decade** [comment]
> Hi [@PatrickRen](https://github.com/PatrickRen), is there an official solution on this issue now?

The migrant issue [FLINK-34883 on Apache Jira](https://issues.apache.org/jira/browse/FLINK-34883) is marked as resolved via master: 94a0415475e7040cc6a61e9bd8aca9c3ccea80ad
