### ISSUE TITLE
MySqlSource.<EventRecord>builder().tableList无法按照指定顺序全量获取数据

### ISSUE THREAD

**Issue by WuSuoWeiLi** [apache/flink-cdc#3109]
MySqlSource.<EventRecord>builder().tableList无法按照指定顺序全量获取数据，某些业务层表之间有依赖关系，需要按照表顺序进行全量抓取数据：
建议：TableDiscoveryUtils.java 工具类中按指定顺序提取表数据
// Fetch table data is read in the specified table order
        List<TableId> sortedCapturedTableIds = new ArrayList<>();
        Map<String, TableId> mapping =
                capturedTableIds.stream()
                        .collect(
                                Collectors.toMap(
                                        k -> String.format("%s.%s", k.catalog(), k.table()),
                                        v -> v,
                                        (v1, v2) -> v2));
        for (String table : tableList) {
            sortedCapturedTableIds.add(mapping.get(table));
        }
        return sortedCapturedTableIds;

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
