### ISSUE TITLE
[Bug]MySqlSource An error occurred when adding a table to the table.include.list attribute

### ISSUE THREAD

**Issue by xiahuya** [apache/flink-cdc#3112]
Flink-cdc Version : 2.3.0 

When I was using MySqlSource, when starting the program for the first time, the 'table.include.list'=sqluser.pa_adm，and enable checkpoint，The data in the table ‘sqluser.pa_adm’  is normal.

When I modify 'table.include.list'=sqluser.pa_adm，sqluser.pa_person，program recovery from savepoint，The program started reporting an error and was unable to capture data for sqluser.pa_person，throwing exceptions 'Encountered change event 'Event{header=EventHeaderV4{timestamp=170917       7391000, eventType=TABLE_MAP, serverId=1, headerLength=19, dataLength=117, nextPosition=769436194, flags=0}, data=TableMapEventData{tableId=5303, database='sqluser', table='pa_person', columnTypes=8, 15, 18, 18, 18, 18, 18, 18, 18, 18, 18, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 1, 15, columnMetadata=0, 192,        0, 0, 0, 0, 0, 0, 0, 0, 0, 192, 96, 96, 96, 96, 96, 384, 96, 96, 384, 30, 30, 30, 30, 0, 96, columnNullability={5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 1       9, 20, 21, 22, 23, 24, 25, 26}, eventMetadata=TableMapEventMetadata{signedness={1}, defaultCharset=33, charsetCollations=null, columnCharsets=null, columnNames=null,        setStrValues=null, enumStrValues=null, geometryTypes=null, simplePrimaryKeys=null, primaryKeysWithPrefix=null, enumAndSetDefaultCharset=null, enumAndSetColumnCharse       ts=null,visibility=null}}}' at offset {transaction_id=null, ts_sec=1709177391, file=binlog.000476, pos=769435520, server_id=1, event=3} for table sqluser.pa_person whose schema isn't known to this connector. One possible cause is an incomplete database history topic. Take a new snapshot in this case.'

I will read the source code later，When the program is restarted and restored from state, the schema of the  added table sqluser.pa_person no exists

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
