### ISSUE TITLE
[Doc]文档对应的网址提示404，“There isn't a GitHub Pages site here.”

### ISSUE THREAD

**Issue by MrCh1ppy** [apache/flink-cdc#3113]
请问是文档的页面配置出错了，
还是文档需要本地构建，
我无法访问到flink cdc的文档（https://ververica.github.io/flink-cdc-connectors/master/）

**Comment by liyichencc** [comment]
可以先使用这个地址：https://apache.github.io/flink-cdc/master/

**Comment by MrCh1ppy** [comment]
好的，十分感谢
