### ISSUE TITLE
官网404，好几天了。

### ISSUE THREAD

**Issue by zhong2312** [apache/flink-cdc#3115]
![image](https://github.com/apache/flink-cdc/assets/4153607/7b109456-9017-4330-9cbd-44e5c51f9bd0)

**Comment by MrCh1ppy** [comment]
文档可以暂时看这个https://apache.github.io/flink-cdc/master/content/overview/index.html

**Comment by hnbian** [comment]
这个是md 里面的链接地址错误, 已经提交了, pr 修复这个问题  https://github.com/apache/flink-cdc/pull/3106

**Comment by PatrickRen** [comment]
New documentation website is available at https://nightlies.apache.org/flink/flink-cdc-docs-stable/
