### ISSUE TITLE
后续有计划支持，多物理库分库分表同步、相同数据库合并源、通过SQL创建整库同步这几个功能吗？

### ISSUE THREAD

**Issue by zhong2312** [apache/flink-cdc#3116]
后续有计划支持，多物理库分库分表同步、相同数据库合并源、通过SQL创建整库同步这几个功能吗？
或者说这几个功能符合Flink-CDC的发展路线不？

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
