### ISSUE TITLE
[bug] [Pipeline-cdc] The new table in the pipeline-cdc cannot synchronize the table structure and data

### ISSUE THREAD

**Issue by avatarTaier** [apache/flink-cdc#3123]
The new table in the pipeline-cdc cannot synchronize the table structure and data

**Comment by avatarTaier** [comment]
@ruanhang1993

**Comment by PatrickRen** [comment]
Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
