### ISSUE TITLE
使用oracle-cdc ，table api的方式一直监听不到数据，但是也不报错

### ISSUE THREAD

**Issue by 409713427** [apache/flink-cdc#3135]
![2641723e725067b7dca59018802d172](https://github.com/apache/flink-cdc/assets/50270110/a84d312f-932f-4db4-afd9-5cd4f973f1ac)
![0182f12246712d6be3b8d2878fca6b4](https://github.com/apache/flink-cdc/assets/50270110/807e84e4-792e-49ff-b6cf-690f44df52db)
换成jdbc的方式能够正常读取到数据，这是oracle-cdc的bug吗？

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
