### ISSUE TITLE
mysql cdc 3.0, when start from savepoint, the modify of startup.options is not effective

### ISSUE THREAD

**Issue by sufeng23c** [apache/flink-cdc#3136]
First, we config the starup.options as `initial`, it works well.
Then, we do savepoint by command `flink savepoint xx`.
Last, we config the startup.options as `latest`, and add a new table, start task from the savepoint.
The result is that the new added table still perfoms initial snapshot and new changes.
Is it possible that the above scenario is not supported?

**Comment by loserwang1024** [comment]
@sufeng23c  At present, it is not support. The state of this two mode's enumerator are not same, which is HybridPendingSplitsState and StreamPendingSplitsState.  By the way,  please create issue in FLINK Jira later

**Comment by sufeng23c** [comment]
OK, thank you.
