### ISSUE TITLE
文档页面404

### ISSUE THREAD

**Issue by legen618** [apache/flink-cdc#3138]

**Comment by gtk96** [comment]
@legen618 https://nightlies.apache.org/flink/flink-cdc-docs-release-3.0/docs/connectors/cdc-connectors/overview/

**Comment by hirolee88** [comment]
我也发现了

**Comment by hirolee88** [comment]
@legen618 I'm willing to take this, Please assign to me. Thank you~

**Comment by legen618** [comment]
> @legen618 https://nightlies.apache.org/flink/flink-cdc-docs-release-3.0/docs/connectors/cdc-connectors/overview/

@gtk96  Thank you! It helps a lot.

**Comment by legen618** [comment]
@hirolee88 Sorry, I'm afraid I don't have the right to do assignment in this Repository.

> According to rules of Github:
> Anyone with write access to a repository can assign issues and pull requests.

**Comment by loserwang1024** [comment]
The community is migrating and refractor the website content.

**Comment by PatrickRen** [comment]
New documentation website is available at https://nightlies.apache.org/flink/flink-cdc-docs-stable/
