### ISSUE TITLE
How to do MySQL to MySQL pipeline 

### ISSUE THREAD

**Issue by ysmintor** [apache/flink-cdc#3140]
Hi, I just found out demo of MySQL to Doris, But I want to do a whole sync database of MySQL to another MySQL. flink-cdc-pipeline-connector-mysql is just for source. How about the sink still is MySQL?

Cloud anyone tell me some information to implement.

**Comment by ihadoop** [comment]
you can create sink mysql table

```sql
CREATE TABLE mysql_sink (
  `id`  bigint ,
  `s_name` varchar(100)  ,
  `s_int` bigint,
 PRIMARY KEY(id) NOT ENFORCED 
) WITH (
 'connector' = 'jdbc',
'driver' = 'com.mysql.cj.jdbc.Driver',
'url' = 'jdbc:mysql://192.168.1.15:3306/cdc?serverTimezone=UTC&useSSL=false',
 'username' = 'root',
 'password' = '111111',
 'table-name' = 't_t'
);


insert into mysql_sink select * from cdc_table
```

**Comment by KiwiGeorge** [comment]
Owner said mysql2mysql still not support even though there is source code

**Comment by ysmintor** [comment]
> Owner said mysql2mysql still not support even though there is source code

Oh, Thank you. I have found some DataStream method to handle which take CDC DDL to create corelated table in sink. I also found third party Dinky which is a streaming process platform based on Flink that already implement MySQL to MySQL  in their way. So I hope at someday FlinkCDC 3.0+ will implement those features.

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
