### ISSUE TITLE
flinkcdc3 official website operation error

### ISSUE THREAD

**Issue by Tangsonghuai** [apache/flink-cdc#3457]
My question is below ，please help

**Comment by Tangsonghuai** [comment]
When I followed the official website's operating documentation step by step, an error message was reported and I don't know how to solve it

![屏幕截图 2024-07-07 103633](https://github.com/apache/flink-cdc/assets/34538205/2195b299-f33f-40c9-95d3-1fb8e141ec28)

then i run this script called bash  'bash flink-cdc.sh mysql-to-doris.yaml'
it goes wrong
`java.lang.NoClassDefFoundError: Could not initialize class io.debezium.connector.mysql.MySqlConnectorConfig`

The following is the version I use

1. flink1.18
2.flinkcdc3.1
by the way : i follow this doc 'https://nightlies.apache.org/flink/flink-cdc-docs-release-3.1/zh/docs/get-started/quickstart/mysql-to-doris/'


please help!

**Comment by Tangsonghuai** [comment]
this server is done! flinkcdc3.0 can work

**Comment by open617** [comment]
Has the problem been resolved

**Comment by yuxiqian** [comment]
`mysql-connector-java` should be placed to `$FLINK_HOME/lib` or be passed with CDC `--jar` argument.

It is preferred to report issues / request new features on [GitHub Discussions](https://github.com/apache/flink-cdc/discussions), [Flink JIRA](https://issues.apache.org/jira/projects/FLINK/summary), Apache mailing list, etc. Questions on GitHub issues may not be actively checked, and will be closed without further explanation.

**Comment by open617** [comment]
thank


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/flink-cdc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月11日(星期四) 下午5:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/flink-cdc] flinkcdc3 official website operation error (Issue #3457)





 
mysql-connector-java should be placed to $FLINK_HOME/lib or be passed with CDC --jar argument.
 
It is preferred to report issues / request new features on GitHub Discussions, Flink JIRA, Apache mailing list, etc. Questions on GitHub issues may not be actively checked, and will be closed without further explanation.
